In [2]:
import pandas as pd

In [3]:
pd.set_option('display.max_colwidth', None)

df = pd.read_csv("tuning_runs.csv")

df = df[df['pretrained'] == False]
# df = df[~df['weight_decay'].isin([1.0, 0.5])]

len(df)

1200

In [5]:
col_to_keep = ['loss_fn', 'seed', 'pretrained', 'efficient_loss',
       'weight_decay', 'learning_rate', 'epoch',
       'run_name', 'ckpt_pt', 'wandb_path',
       'val_loss',
       'val_true_cxr_acc_at_1', 'val_true_cxr_acc_at_5', 'val_true_cxr_acc_at_10',
       'val_label_acc_at_1', 'val_label_acc_at_5', 'val_label_acc_at_10',
#        'val_label_precision_at_1', 'val_label_precision_at_5', 'val_label_precision_at_10',
       ]
df = df[col_to_keep]

In [6]:
idx = df.groupby(['loss_fn'])['val_loss'].idxmin()
df.loc[idx]

,loss_fn,seed,pretrained,efficient_loss,weight_decay,learning_rate,epoch,run_name,ckpt_pt,wandb_path,val_loss,val_true_cxr_acc_at_1,val_true_cxr_acc_at_5,val_true_cxr_acc_at_10,val_label_acc_at_1,val_label_acc_at_5,val_label_acc_at_10
955,clip,0,False,True,0.01,0.0005,5,20240510_012358_7179,/gpfs/data/ranganathlab/symile_tmp/cxr_prediction_age_sex_ckpts/20240510_012358_7179/epoch=5-val_loss=15.2400.ckpt,https://wandb.ai/rajesh-lab/symile/runs/4ozyoaxp,15.239988,0.0,0.40,0.700,0.05,0.475,0.825
556,symile,0,False,True,0.10,0.0005,6,20240509_130110_1706,/gpfs/data/ranganathlab/symile_tmp/cxr_prediction_age_sex_ckpts/20240509_130110_1706/epoch=6-val_loss=4.1993.ckpt,https://wandb.ai/rajesh-lab/symile/runs/qtklyg5d,4.199282,0.0,0.25,0.475,0.10,0.325,0.625

In [7]:
df[df['loss_fn']=="symile"].sort_values(by="val_loss", ascending=True).head(1)

,loss_fn,seed,pretrained,efficient_loss,weight_decay,learning_rate,epoch,run_name,ckpt_pt,wandb_path,val_loss,val_true_cxr_acc_at_1,val_true_cxr_acc_at_5,val_true_cxr_acc_at_10,val_label_acc_at_1,val_label_acc_at_5,val_label_acc_at_10
556,symile,0,False,True,0.1,0.0005,6,20240509_130110_1706,/gpfs/data/ranganathlab/symile_tmp/cxr_prediction_age_sex_ckpts/20240509_130110_1706/epoch=6-val_loss=4.1993.ckpt,https://wandb.ai/rajesh-lab/symile/runs/qtklyg5d,4.199282,0.0,0.25,0.475,0.1,0.325,0.625

In [8]:
idx = df.groupby(['loss_fn'])['val_true_cxr_acc_at_1'].idxmax()
df.loc[idx]

,loss_fn,seed,pretrained,efficient_loss,weight_decay,learning_rate,epoch,run_name,ckpt_pt,wandb_path,val_loss,val_true_cxr_acc_at_1,val_true_cxr_acc_at_5,val_true_cxr_acc_at_10,val_label_acc_at_1,val_label_acc_at_5,val_label_acc_at_10
1198,clip,0,False,True,0.10,0.0005,48,20240509_125629_4773,/gpfs/data/ranganathlab/symile_tmp/cxr_prediction_age_sex_ckpts/20240509_125629_4773/epoch=48-val_loss=17.8729.ckpt,https://wandb.ai/rajesh-lab/symile/runs/tzntq895,17.872889,0.2,0.375,0.50,0.20,0.475,0.675
234,symile,0,False,True,0.01,0.0100,34,20240509_001808_6497,/gpfs/data/ranganathlab/symile_tmp/cxr_prediction_age_sex_ckpts/20240509_001808_6497/epoch=34-val_loss=4.3857.ckpt,https://wandb.ai/rajesh-lab/symile/runs/9jgtz5lv,4.385698,0.2,0.375,0.55,0.25,0.500,0.700

In [10]:
df[df['loss_fn']=="symile"].sort_values(by="val_true_cxr_acc_at_1", ascending=False).head(1)

,loss_fn,seed,pretrained,efficient_loss,weight_decay,learning_rate,epoch,run_name,ckpt_pt,wandb_path,val_loss,val_true_cxr_acc_at_1,val_true_cxr_acc_at_5,val_true_cxr_acc_at_10,val_label_acc_at_1,val_label_acc_at_5,val_label_acc_at_10
234,symile,0,False,True,0.01,0.01,34,20240509_001808_6497,/gpfs/data/ranganathlab/symile_tmp/cxr_prediction_age_sex_ckpts/20240509_001808_6497/epoch=34-val_loss=4.3857.ckpt,https://wandb.ai/rajesh-lab/symile/runs/9jgtz5lv,4.385698,0.2,0.375,0.55,0.25,0.5,0.7