In [1]:
import pandas as pd

In [12]:
pd.set_option('display.max_colwidth', None)

df = pd.read_csv("diff_seeds.csv")

df = df[df['pretrained'] == False]
# df = df[~df['weight_decay'].isin([1.0, 0.5])]

len(df)

2000

In [16]:
col_to_keep = ['loss_fn', 'seed', 'pretrained', 'labs_model',
       'weight_decay', 'learning_rate', 'epoch',
       'run_name', 'ckpt_pt', 'wandb_path',
       'val_loss',
       'val_true_cxr_acc_at_1', 'val_true_cxr_acc_at_5', 'val_true_cxr_acc_at_10',
       'val_label_acc_at_1', 'val_label_acc_at_5', 'val_label_acc_at_10',
#        'val_label_precision_at_1', 'val_label_precision_at_5', 'val_label_precision_at_10',
       ]
df = df[col_to_keep]

In [17]:
idx = df.groupby(['loss_fn', 'seed'])['val_loss'].idxmin()
df.loc[idx]

,loss_fn,seed,pretrained,labs_model,weight_decay,learning_rate,epoch,run_name,ckpt_pt,wandb_path,val_loss,val_true_cxr_acc_at_1,val_true_cxr_acc_at_5,val_true_cxr_acc_at_10,val_label_acc_at_1,val_label_acc_at_5,val_label_acc_at_10
1030,clip,0,False,mlp,0.1,0.01,30,20240428_054506_3065,/gpfs/scratch/as16583/ckpts/cxr_prediction/20240428_054506_3065/epoch=30-val_loss=15.1978.ckpt,https://wandb.ai/rajesh-lab/symile/runs/44w9vmsz,15.197756,0.08,0.40,0.60,0.16,0.60,0.76
1127,clip,1,False,mlp,0.1,0.01,27,20240506_173032_5493,/gpfs/scratch/as16583/ckpts/cxr_prediction/20240506_173032_5493/epoch=27-val_loss=15.2534.ckpt,https://wandb.ai/rajesh-lab/symile/runs/29k0gebz,15.253416,0.08,0.40,0.52,0.16,0.64,0.68
1226,clip,2,False,mlp,0.1,0.01,26,20240506_173229_7203,/gpfs/scratch/as16583/ckpts/cxr_prediction/20240506_173229_7203/epoch=26-val_loss=15.3531.ckpt,https://wandb.ai/rajesh-lab/symile/runs/snfi8q97,15.353104,0.16,0.24,0.40,0.24,0.40,0.60
1328,clip,3,False,mlp,0.1,0.01,28,20240506_173242_9859,/gpfs/scratch/as16583/ckpts/cxr_prediction/20240506_173242_9859/epoch=28-val_loss=15.0589.ckpt,https://wandb.ai/rajesh-lab/symile/runs/djhtorpw,15.058857,0.20,0.40,0.48,0.24,0.60,0.68
1427,clip,4,False,mlp,0.1,0.01,27,20240506_184330_3917,/gpfs/scratch/as16583/ckpts/cxr_prediction/20240506_184330_3917/epoch=27-val_loss=15.1677.ckpt,https://wandb.ai/rajesh-lab/symile/runs/e8js2aja,15.167657,0.08,0.24,0.44,0.16,0.48,0.72
1529,clip,5,False,mlp,0.1,0.01,29,20240506_184510_5433,/gpfs/scratch/as16583/ckpts/cxr_prediction/20240506_184510_5433/epoch=29-val_loss=15.2266.ckpt,https://wandb.ai/rajesh-lab/symile/runs/rk0k6yan,15.226581,0.04,0.24,0.36,0.08,0.40,0.64
1626,clip,6,False,mlp,0.1,0.01,26,20240506_184653_4559,/gpfs/scratch/as16583/ckpts/cxr_prediction/20240506_184653_4559/epoch=26-val_loss=15.3715.ckpt,https://wandb.ai/rajesh-lab/symile/runs/tckenxub,15.371500,0.04,0.28,0.44,0.20,0.52,0.64
1728,clip,7,False,mlp,0.1,0.01,28,20240506_195629_4949,/gpfs/scratch/as16583/ckpts/cxr_prediction/20240506_195629_4949/epoch=28-val_loss=15.1288.ckpt,https://wandb.ai/rajesh-lab/symile/runs/rn63fzy3,15.128796,0.12,0.20,0.32,0.20,0.36,0.56
1835,clip,8,False,mlp,0.1,0.01,35,20240506_195811_8206,/gpfs/scratch/as16583/ckpts/cxr_prediction/20240506_195811_8206/epoch=35-val_loss=15.2179.ckpt,https://wandb.ai/rajesh-lab/symile/runs/itgvl7o6,15.217910,0.08,0.16,0.24,0.12,0.24,0.32
1935,clip,9,False,mlp,0.1,0.01,35,20240506_200030_2465,/gpfs/scratch/as16583/ckpts/cxr_prediction/20240506_200030_2465/epoch=35-val_loss=15.2884.ckpt,https://wandb.ai/rajesh-lab/symile/runs/ilhb0jpj,15.288416,0.12,0.24,0.32,0.24,0.56,0.64
33,symile,0,False,mlp,0.1,0.01,33,20240427_235312_1971,/gpfs/scratch/as16583/ckpts/cxr_prediction/20240427_235312_1971/epoch=33-val_loss=4.5781.ckpt,https://wandb.ai/rajesh-lab/symile/runs/uld2rmme,4.578073,0.00,0.16,0.32,0.08,0.40,0.60
142,symile,1,False,mlp,0.1,0.01,42,20240506_135216_4057,/gpfs/scratch/as16583/ckpts/cxr_prediction/20240506_135216_4057/epoch=42-val_loss=4.4042.ckpt,https://wandb.ai/rajesh-lab/symile/runs/qjdxbwod,4.404177,0.08,0.24,0.36,0.16,0.40,0.48
232,symile,2,False,mlp,0.1,0.01,32,20240506_135325_2929,/gpfs/scratch/as16583/ckpts/cxr_prediction/20240506_135325_2929/epoch=32-val_loss=4.4911.ckpt,https://wandb.ai/rajesh-lab/symile/runs/bzw01x36,4.491144,0.12,0.32,0.44,0.16,0.52,0.80
329,symile,3,False,mlp,0.1,0.01,29,20240506_135515_0621,/gpfs/scratch/as16583/ckpts/cxr_prediction/20240506_135515_0621/epoch=29-val_loss=4.4966.ckpt,https://wandb.ai/rajesh-lab/symile/runs/smbougz3,4.496629,0.04,0.12,0.28,0.04,0.28,0.52
444,symile,4,False,mlp,0.1,0.01,44,20240506_150424_7821,/gpfs/scratch/as16583/ckpts/cxr_prediction/20240506_150424_7821/epoch=44-val_loss=4.4143.ckpt,https://wandb.ai/rajesh-lab/symile/runs/h2d0va6j,4.414277,0.16,0.36,0.40,0.20,0.44,0.56
535,symile,5,False,mlp,0.1,0.01,35,20240506_150630_3681,/gpfs/scratch/as16583/ckpts/cxr_prediction/20240506_150630_3681/epoch=35-val_loss=4.3960.ckpt,https://wandb.ai/rajesh-lab/symile/runs/ll2j2q12,4.396027,0.08,0.16,0.36,0.16,0.36,0.60
639,symile,6,False,mlp,0.1,0.01,39,20240506_150719_8710,/gpfs/scratch/as16583/ckpts/cxr_prediction/20240506_150719_8710/epoch=39-val_loss=4.4500.ckpt,https://wandb.ai/rajesh-lab/symile/runs/47qxcods,4.450010,0.04,0.28,0.48,0.08,0.44,0.80
738,symile,7,False,mlp,0.1,0.01,38,20240506_161710_7113,/gpfs/scratch/as16583/ckpts/cxr_prediction/20240506_161710_7113/epoch=38-val_loss=4.4608.ckpt,https://wandb.ai/rajesh-lab/symile/runs/xf74gnf3,4.460777,0.16,0.28,0.36,0.28,0.60,0.72
837,symile,8,False,mlp,0.1,0.01,37,20240506_161931_8852,/gpfs/scratch/as16583/ckpts/cxr_prediction/20240506_161931_8852/epoch=37-val_loss=4.3655.ckpt,https://wandb.ai/rajesh-lab/symile/runs/aazdpbet,4.365502,0.04,0.16,0.52,0.12,0.52,0.84
929,symile,9,False,mlp,0.1,0.01,29,20240506_161954_8355,/gpfs/scratch/as16583/ckpts/cxr_prediction/20240506_161954_8355/epoch=29-val_loss=4.4156.ckpt,https://wandb.ai/rajesh-lab/symile/runs/ylzu01xf,4.415630,0.04,0.32,0.44,0.12,0.52,0.68

In [ ]:
df[df['loss_fn']=="symile"].sort_values(by="val_loss", ascending=True).head(1)

In [22]:
idx = df.groupby(['loss_fn', 'seed'])['val_true_cxr_acc_at_1'].idxmax()
df.loc[idx]

,loss_fn,seed,pretrained,labs_model,weight_decay,learning_rate,epoch,run_name,ckpt_pt,wandb_path,val_loss,val_true_cxr_acc_at_1,val_true_cxr_acc_at_5,val_true_cxr_acc_at_10,val_label_acc_at_1,val_label_acc_at_5,val_label_acc_at_10
1024,clip,0,False,mlp,0.1,0.01,24,20240428_054506_3065,/gpfs/scratch/as16583/ckpts/cxr_prediction/20240428_054506_3065/epoch=24-val_loss=15.4240.ckpt,https://wandb.ai/rajesh-lab/symile/runs/44w9vmsz,15.424027,0.20,0.28,0.28,0.20,0.36,0.64
1129,clip,1,False,mlp,0.1,0.01,29,20240506_173032_5493,/gpfs/scratch/as16583/ckpts/cxr_prediction/20240506_173032_5493/epoch=29-val_loss=15.8761.ckpt,https://wandb.ai/rajesh-lab/symile/runs/29k0gebz,15.876101,0.16,0.28,0.28,0.20,0.40,0.56
1216,clip,2,False,mlp,0.1,0.01,16,20240506_173229_7203,/gpfs/scratch/as16583/ckpts/cxr_prediction/20240506_173229_7203/epoch=16-val_loss=15.7014.ckpt,https://wandb.ai/rajesh-lab/symile/runs/snfi8q97,15.701429,0.16,0.32,0.40,0.16,0.52,0.76
1328,clip,3,False,mlp,0.1,0.01,28,20240506_173242_9859,/gpfs/scratch/as16583/ckpts/cxr_prediction/20240506_173242_9859/epoch=28-val_loss=15.0589.ckpt,https://wandb.ai/rajesh-lab/symile/runs/djhtorpw,15.058857,0.20,0.40,0.48,0.24,0.60,0.68
1432,clip,4,False,mlp,0.1,0.01,32,20240506_184330_3917,/gpfs/scratch/as16583/ckpts/cxr_prediction/20240506_184330_3917/epoch=32-val_loss=15.8157.ckpt,https://wandb.ai/rajesh-lab/symile/runs/e8js2aja,15.815717,0.16,0.32,0.52,0.24,0.52,0.76
1512,clip,5,False,mlp,0.1,0.01,12,20240506_184510_5433,/gpfs/scratch/as16583/ckpts/cxr_prediction/20240506_184510_5433/epoch=12-val_loss=15.7475.ckpt,https://wandb.ai/rajesh-lab/symile/runs/rk0k6yan,15.747478,0.12,0.32,0.40,0.16,0.40,0.64
1635,clip,6,False,mlp,0.1,0.01,35,20240506_184653_4559,/gpfs/scratch/as16583/ckpts/cxr_prediction/20240506_184653_4559/epoch=35-val_loss=16.2911.ckpt,https://wandb.ai/rajesh-lab/symile/runs/tckenxub,16.291149,0.16,0.24,0.44,0.24,0.36,0.68
1733,clip,7,False,mlp,0.1,0.01,33,20240506_195629_4949,/gpfs/scratch/as16583/ckpts/cxr_prediction/20240506_195629_4949/epoch=33-val_loss=15.4885.ckpt,https://wandb.ai/rajesh-lab/symile/runs/rn63fzy3,15.488484,0.20,0.28,0.44,0.28,0.44,0.68
1831,clip,8,False,mlp,0.1,0.01,31,20240506_195811_8206,/gpfs/scratch/as16583/ckpts/cxr_prediction/20240506_195811_8206/epoch=31-val_loss=15.5303.ckpt,https://wandb.ai/rajesh-lab/symile/runs/itgvl7o6,15.530315,0.16,0.20,0.40,0.28,0.48,0.72
1972,clip,9,False,mlp,0.1,0.01,72,20240506_200030_2465,/gpfs/scratch/as16583/ckpts/cxr_prediction/20240506_200030_2465/epoch=72-val_loss=36.0605.ckpt,https://wandb.ai/rajesh-lab/symile/runs/ilhb0jpj,36.060463,0.20,0.32,0.44,0.24,0.68,0.88
39,symile,0,False,mlp,0.1,0.01,39,20240427_235312_1971,/gpfs/scratch/as16583/ckpts/cxr_prediction/20240427_235312_1971/epoch=39-val_loss=4.6411.ckpt,https://wandb.ai/rajesh-lab/symile/runs/uld2rmme,4.641066,0.20,0.48,0.52,0.24,0.72,0.84
153,symile,1,False,mlp,0.1,0.01,53,20240506_135216_4057,/gpfs/scratch/as16583/ckpts/cxr_prediction/20240506_135216_4057/epoch=53-val_loss=5.1663.ckpt,https://wandb.ai/rajesh-lab/symile/runs/qjdxbwod,5.166313,0.16,0.28,0.32,0.24,0.40,0.60
219,symile,2,False,mlp,0.1,0.01,19,20240506_135325_2929,/gpfs/scratch/as16583/ckpts/cxr_prediction/20240506_135325_2929/epoch=19-val_loss=4.7406.ckpt,https://wandb.ai/rajesh-lab/symile/runs/bzw01x36,4.740626,0.20,0.24,0.28,0.20,0.36,0.56
349,symile,3,False,mlp,0.1,0.01,49,20240506_135515_0621,/gpfs/scratch/as16583/ckpts/cxr_prediction/20240506_135515_0621/epoch=49-val_loss=5.1097.ckpt,https://wandb.ai/rajesh-lab/symile/runs/smbougz3,5.109733,0.20,0.24,0.52,0.20,0.44,0.64
432,symile,4,False,mlp,0.1,0.01,32,20240506_150424_7821,/gpfs/scratch/as16583/ckpts/cxr_prediction/20240506_150424_7821/epoch=32-val_loss=4.5202.ckpt,https://wandb.ai/rajesh-lab/symile/runs/h2d0va6j,4.520171,0.16,0.32,0.52,0.20,0.56,0.72
550,symile,5,False,mlp,0.1,0.01,50,20240506_150630_3681,/gpfs/scratch/as16583/ckpts/cxr_prediction/20240506_150630_3681/epoch=50-val_loss=5.1327.ckpt,https://wandb.ai/rajesh-lab/symile/runs/ll2j2q12,5.132687,0.16,0.20,0.28,0.24,0.28,0.52
635,symile,6,False,mlp,0.1,0.01,35,20240506_150719_8710,/gpfs/scratch/as16583/ckpts/cxr_prediction/20240506_150719_8710/epoch=35-val_loss=4.6283.ckpt,https://wandb.ai/rajesh-lab/symile/runs/47qxcods,4.628318,0.16,0.28,0.40,0.24,0.44,0.64
738,symile,7,False,mlp,0.1,0.01,38,20240506_161710_7113,/gpfs/scratch/as16583/ckpts/cxr_prediction/20240506_161710_7113/epoch=38-val_loss=4.4608.ckpt,https://wandb.ai/rajesh-lab/symile/runs/xf74gnf3,4.460777,0.16,0.28,0.36,0.28,0.60,0.72
828,symile,8,False,mlp,0.1,0.01,28,20240506_161931_8852,/gpfs/scratch/as16583/ckpts/cxr_prediction/20240506_161931_8852/epoch=28-val_loss=4.6823.ckpt,https://wandb.ai/rajesh-lab/symile/runs/aazdpbet,4.682275,0.16,0.36,0.44,0.24,0.60,0.68
930,symile,9,False,mlp,0.1,0.01,30,20240506_161954_8355,/gpfs/scratch/as16583/ckpts/cxr_prediction/20240506_161954_8355/epoch=30-val_loss=4.6471.ckpt,https://wandb.ai/rajesh-lab/symile/runs/ylzu01xf,4.647052,0.16,0.28,0.44,0.16,0.36,0.68

In [21]:
df[(df['loss_fn']=="symile")&(df['seed']==9)].sort_values(by="val_true_cxr_acc_at_1", ascending=False).head(1)

,loss_fn,seed,pretrained,labs_model,weight_decay,learning_rate,epoch,run_name,ckpt_pt,wandb_path,val_loss,val_true_cxr_acc_at_1,val_true_cxr_acc_at_5,val_true_cxr_acc_at_10,val_label_acc_at_1,val_label_acc_at_5,val_label_acc_at_10
988,symile,9,False,mlp,0.1,0.01,88,20240506_161954_8355,/gpfs/scratch/as16583/ckpts/cxr_prediction/20240506_161954_8355/epoch=88-val_loss=7.7888.ckpt,https://wandb.ai/rajesh-lab/symile/runs/ylzu01xf,7.788838,0.16,0.2,0.28,0.2,0.32,0.56