In [4]:
import pandas as pd

In [15]:
pd.set_option('display.max_colwidth', None)
df = pd.read_csv("test.csv")

In [19]:
metrics = ["true_cxr_acc", "label_acc", "label_precision"]
df = df[df['metric'].isin(metrics)]

In [30]:
df[df['seed']==9]

     loss_fn  seed              run_name           metric  value   k
531   symile     9  20240507_140937_5555  label_precision  0.160   1
532   symile     9  20240507_140937_5555  label_precision  0.104   5
533   symile     9  20240507_140937_5555  label_precision  0.096  10
534   symile     9  20240507_140937_5555        label_acc  0.160   1
535   symile     9  20240507_140937_5555        label_acc  0.360   5
536   symile     9  20240507_140937_5555        label_acc  0.680  10
537   symile     9  20240507_140937_5555     true_cxr_acc  0.160   1
538   symile     9  20240507_140937_5555     true_cxr_acc  0.280   5
539   symile     9  20240507_140937_5555     true_cxr_acc  0.440  10
1071    clip     9  20240507_141240_9342  label_precision  0.240   1
1072    clip     9  20240507_141240_9342  label_precision  0.144   5
1073    clip     9  20240507_141240_9342  label_precision  0.120  10
1074    clip     9  20240507_141240_9342        label_acc  0.240   1
1075    clip     9  20240507_141240_9342        label_acc  0.680   5
1076    clip     9  20240507_141240_9342        label_acc  0.880  10
1077    clip     9  20240507_141240_9342     true_cxr_acc  0.200   1
1078    clip     9  20240507_141240_9342     true_cxr_acc  0.320   5
1079    clip     9  20240507_141240_9342     true_cxr_acc  0.440  10

In [14]:
df[(df["metric"]=="true_cxr_acc") & (df['k']==5)]

     loss_fn              run_name        metric  value  k
52    symile  20240507_140550_9990  true_cxr_acc   0.48  5
106   symile  20240507_140550_6274  true_cxr_acc   0.28  5
160   symile  20240507_140636_8415  true_cxr_acc   0.24  5
214   symile  20240507_140636_8898  true_cxr_acc   0.24  5
268   symile  20240507_140735_3620  true_cxr_acc   0.32  5
322   symile  20240507_140735_3804  true_cxr_acc   0.20  5
376   symile  20240507_140843_4264  true_cxr_acc   0.28  5
430   symile  20240507_140843_0125  true_cxr_acc   0.28  5
484   symile  20240507_140843_6161  true_cxr_acc   0.36  5
538   symile  20240507_140937_5555  true_cxr_acc   0.28  5
592     clip  20240507_140937_9119  true_cxr_acc   0.28  5
646     clip  20240507_140937_5180  true_cxr_acc   0.28  5
700     clip  20240507_141038_5573  true_cxr_acc   0.32  5
754     clip  20240507_141038_1689  true_cxr_acc   0.40  5
808     clip  20240507_141038_0518  true_cxr_acc   0.32  5
862     clip  20240507_141139_7830  true_cxr_acc   0.32  5
916     clip  20240507_141139_0667  true_cxr_acc   0.24  5
970     clip  20240507_141139_1160  true_cxr_acc   0.28  5
1024    clip  20240507_141240_1408  true_cxr_acc   0.20  5
1078    clip  20240507_141240_9342  true_cxr_acc   0.32  5

In [ ]:
idx = df.groupby(['loss_fn', 'seed'])['val_loss'].idxmin()
df.loc[idx]

In [ ]:
df[df['loss_fn']=="symile"].sort_values(by="val_loss", ascending=True).head(1)

In [ ]:
idx = df.groupby(['loss_fn', 'seed'])['val_true_cxr_acc_at_1'].idxmax()
df.loc[idx]

In [ ]:
df[(df['loss_fn']=="symile")&(df['seed']==9)].sort_values(by="val_true_cxr_acc_at_1", ascending=False).head(1)