In [2]:
from collections import Counter
import json
import pandas as pd

In [2]:
pt = "/gpfs/scratch/as16583/symile/src/high_dim/data_reference.json"
l_dict = json.load(open(pt))

In [9]:
forbidden_list = ["ru", "sv", "pt", "fr", "it", "nl", "id", "zh-CN", "tr", "de", "es", "vi", "pl", "no", "fi", "cs", "cy", "is", "hu",
"he", "hi", "el", "ur", "uk", "th", "te", "ko", "ja"]

In [10]:
# Remove 'synset_id' and languages in the forbidden_list
for class_name, class_dict in l_dict.items():
    # Remove 'synset_id'
    class_dict.pop('synset_id', None)

    # Remove languages in the forbidden_list
    for lang in forbidden_list:
        class_dict.pop(lang, None)

In [11]:
# Create a Counter for each language's values
language_counters = {lang: Counter() for lang in next(iter(l_dict.values())).keys()}

# Count unique values for each language across all class_name entries
for class_name, class_dict in l_dict.items():
    for lang, value in class_dict.items():
        language_counters[lang][value] += 1

# Calculate the overlap between languages
language_overlap = {lang1: {lang2: len(set(language_counters[lang1]) & set(language_counters[lang2]))
                            for lang2 in language_counters if lang1 != lang2}
                    for lang1 in language_counters}

# Print or analyze the overlap
for lang1, overlap_dict in language_overlap.items():
    print(f"Overlap for {lang1}: {overlap_dict}")

Overlap for ar: {'en': 0}
Overlap for en: {'ar': 0}

In [12]:
class_name_overlaps = Counter()

# Identify class names with overlaps and associated languages
for lang1, overlap_dict in language_overlap.items():
    for lang2, count in overlap_dict.items():
        if count > 0:
            class_name_overlaps[(lang1, lang2)] += 1

# You can also print the detailed overlap information
for (lang1, lang2), count in class_name_overlaps.items():
    print(f"\nOverlap details between {lang1} and {lang2} ({count} class names):")
    for class_name, class_dict in l_dict.items():
        values_lang1 = set(value for lang, value in class_dict.items() if lang == lang1)
        values_lang2 = set(value for lang, value in class_dict.items() if lang == lang2)
        common_values = values_lang1 & values_lang2
        if common_values:
            print(f"Class Name: {class_name}, Common Values: {common_values}")

In [ ]:
unique_dict = {}
# for each category, how many unique values are there?
for c, v in l_dict.items():
    # Flatten the values across all languages
    all_values = [value for lang, value in v.items() if lang != 'synset_id']

    # Count the unique values
    unique_value_count = len(set(all_values))

    unique_dict[c] = unique_value_count

count = 0
for k, v in unique_dict.items():
    if v == 20:
        count += 1

In [2]:
pt = "/gpfs/data/ranganathlab/adriel/cv/cv/uk/clip_durations.tsv"
df = pd.read_csv(pt, sep="\t")

In [3]:
df

                               clip  duration[ms]
0      common_voice_uk_38204106.mp3          3420
1      common_voice_uk_25292013.mp3          2160
2      common_voice_uk_36802108.mp3          5076
3      common_voice_uk_32412674.mp3          3384
4      common_voice_uk_27453773.mp3          5508
...                             ...           ...
82802  common_voice_uk_25590027.mp3          5832
82803  common_voice_uk_26225389.mp3          5328
82804  common_voice_uk_29922987.mp3          3420
82805  common_voice_uk_32177066.mp3          2304
82806  common_voice_uk_37898937.mp3          6264

[82807 rows x 2 columns]

In [5]:
df.sort_values(by=['duration[ms]'], ascending=False)

                               clip  duration[ms]
22867  common_voice_uk_27464277.mp3         10584
41851  common_voice_uk_27627008.mp3         10548
74396  common_voice_uk_37620627.mp3         10548
77857  common_voice_uk_28689212.mp3         10548
3857   common_voice_uk_23874288.mp3         10536
...                             ...           ...
20914  common_voice_uk_30590824.mp3             0
14751  common_voice_uk_37444032.mp3             0
16100  common_voice_uk_23559962.mp3             0
29688  common_voice_uk_34120565.mp3             0
37043  common_voice_uk_38223380.mp3             0

[82807 rows x 2 columns]

In [2]:
pt = "/gpfs/scratch/as16583/symile/src/high_dim/data_reference_50.json"
l_dict = json.load(open(pt))

In [4]:
classes = ["goldfish", "great white shark", "hen", "ostrich", "vulture", "bullfrog", "triceratops", "boa constrictor",
           "water snake", "scorpion", "tarantula", "peacock", "hummingbird", "toucan", "goose", "snail", "hermit crab", "flamingo", "pelican", "ladybug",
           "fly", "bee", "ant", "grasshopper", "cricket", "cockroach", "dragonfly", "starfish", "sea urchin", "hamster", "beaver", "zebra", "hog", "hippopotamus",
           "ox", "water buffalo", "bison", "ram", "otter", "skunk", "gorilla", "eel", "aircraft carrier", "ambulance", "apron", "backpack", "bakery", "balloon",
           "bathtub", "bucket"]

In [6]:
langs = [
    "ar", # arabic, 16
    "en", # english, 1
    "ja", # japanese, 12
    "ko", # korean, 23
    "uk", # ukrainian, 14
    "synset_id"
]

In [7]:
l_dict_50 = {key: value for key, value in l_dict.items() if key in classes}

l_dict_50 = {
    key: {subkey: value for subkey, value in value.items() if subkey in langs}
    for key, value in l_dict_50.items()
}

In [8]:
len(l_dict_50)

50

In [9]:
l_dict_50

{'goldfish': {'synset_id': 'n01443537',
  'ar': 'سمكة ذهبية',
  'en': 'goldfish',
  'ja': '金魚',
  'ko': '금붕어',
  'uk': 'золота рибка'},
 'great white shark': {'synset_id': 'n01484850',
  'ar': 'القرش الابيض الكبير',
  'en': 'great white shark',
  'ja': 'ホホジロザメ',
  'ko': '백상어',
  'uk': 'велика біла акула'},
 'hen': {'synset_id': 'n01514859',
  'ar': 'دجاجة',
  'en': 'hen',
  'ja': '鶏',
  'ko': '암탉',
  'uk': 'курка'},
 'ostrich': {'synset_id': 'n01518878',
  'ar': 'نعامة',
  'en': 'ostrich',
  'ja': 'ダチョウ',
  'ko': '타조',
  'uk': 'страус'},
 'vulture': {'synset_id': 'n01616318',
  'ar': 'نسر',
  'en': 'vulture',
  'ja': 'ハゲワシ',
  'ko': '무자비한 사람',
  'uk': 'гриф'},
 'bullfrog': {'synset_id': 'n01641577',
  'ar': 'ضفدع',
  'en': 'bullfrog',
  'ja': 'ウシガエル',
  'ko': '황소개구리',
  'uk': 'жаба-бик'},
 'triceratops': {'synset_id': 'n01704323',
  'ar': 'ترايسيراتوبس',
  'en': 'triceratops',
  'ja': 'トリケラトプス',
  'ko': '트리케라톱스',
  'uk': 'трицератопс'},
 'water snake': {'synset_id': 'n01737021',
  'ar': 'افعى الماء',
  'en': 'water snake',
  'ja': '水蛇',
  'ko': '물뱀',
  'uk': 'водяна змія'},
 'boa constrictor': {'synset_id': 'n01742172',
  'ar': 'أفعى المضيقة',
  'en': 'boa constrictor',
  'ja': 'ボアコンストリクター',
  'ko': '보아뱀',
  'uk': 'удав'},
 'scorpion': {'synset_id': 'n01770393',
  'ar': 'برج العقرب',
  'en': 'scorpion',
  'ja': 'サソリ',
  'ko': '투석기',
  'uk': 'скорпіон'},
 'tarantula': {'synset_id': 'n01774750',
  'ar': 'الرتيلاء',
  'en': 'tarantula',
  'ja': 'タランチュラ',
  'ko': '타란툴라 거미',
  'uk': 'тарантул'},
 'peacock': {'synset_id': 'n01806143',
  'ar': 'الطاووس',
  'en': 'peacock',
  'ja': '孔雀',
  'ko': '공작',
  'uk': 'павич'},
 'hummingbird': {'synset_id': 'n01833805',
  'ar': 'الطائر الطنان',
  'en': 'hummingbird',
  'ja': 'ハチドリ',
  'ko': '벌새',
  'uk': 'колібрі'},
 'toucan': {'synset_id': 'n01843383',
  'ar': 'الطوقان',
  'en': 'toucan',
  'ja': 'オオハシ',
  'ko': '큰부리새',
  'uk': 'тукан'},
 'goose': {'synset_id': 'n01855672',
  'ar': 'أوزة',
  'en': 'goose',
  'ja': 'ガチョウ',
  'ko': '거위',
  'uk': 'гусак'},
 'snail': {'synset_id': 'n01944390',
  'ar': 'حلزون',
  'en': 'snail',
  'ja': 'カタツムリ',
  'ko': '달팽이',
  'uk': 'равлик'},
 'hermit crab': {'synset_id': 'n01986214',
  'ar': 'سلطعون الناسك',
  'en': 'hermit crab',
  'ja': 'ヤドカリ',
  'ko': '소라게',
  'uk': 'рак-відлюдник'},
 'flamingo': {'synset_id': 'n02007558',
  'ar': 'فلامنغو',
  'en': 'flamingo',
  'ja': 'フラミンゴ',
  'ko': '플라밍고',
  'uk': 'фламінго'},
 'pelican': {'synset_id': 'n02051845',
  'ar': 'البجع',
  'en': 'pelican',
  'ja': 'ペリカン',
  'ko': '펠리컨',
  'uk': 'пелікан'},
 'ladybug': {'synset_id': 'n02165456',
  'ar': 'دعسوقة',
  'en': 'ladybug',
  'ja': 'てんとう虫',
  'ko': '무당벌레',
  'uk': 'сонечко'},
 'fly': {'synset_id': 'n02190166',
  'ar': 'يطير',
  'en': 'fly',
  'ja': '飛ぶ',
  'ko': '파리',
  'uk': 'літати'},
 'bee': {'synset_id': 'n02206856',
  'ar': 'نحلة',
  'en': 'bee',
  'ja': '蜂',
  'ko': '벌',
  'uk': 'бджола'},
 'ant': {'synset_id': 'n02219486',
  'ar': 'على',
  'en': 'ant',
  'ja': 'の上',
  'ko': '~에',
  'uk': 'на'},
 'grasshopper': {'synset_id': 'n02226429',
  'ar': 'الجراد',
  'en': 'grasshopper',
  'ja': 'バッタ',
  'ko': '메뚜기',
  'uk': 'коник'},
 'cricket': {'synset_id': 'n02229544',
  'ar': 'كريكيت',
  'en': 'cricket',
  'ja': 'クリケット',
  'ko': '크리켓',
  'uk': 'крикет'},
 'cockroach': {'synset_id': 'n02233338',
  'ar': 'صرصور',
  'en': 'cockroach',
  'ja': 'ゴキブリ',
  'ko': '바퀴벌레',
  'uk': 'тарган'},
 'dragonfly': {'synset_id': 'n02268443',
  'ar': 'اليعسوب',
  'en': 'dragonfly',
  'ja': 'トンボ',
  'ko': '잠자리',
  'uk': 'бабка'},
 'starfish': {'synset_id': 'n02317335',
  'ar': 'نجم البحر',
  'en': 'starfish',
  'ja': 'ヒトデ',
  'ko': '불가사리',
  'uk': 'морська зірка'},
 'sea urchin': {'synset_id': 'n02319095',
  'ar': 'بحر يورتشين',
  'en': 'sea urchin',
  'ja': 'うに',
  'ko': '성게',
  'uk': 'морський їжак'},
 'hamster': {'synset_id': 'n02342885',
  'ar': 'الهامستر',
  'en': 'hamster',
  'ja': 'ハムスター',
  'ko': '햄스터',
  'uk': 'хом&#39;як'},
 'beaver': {'synset_id': 'n02363005',
  'ar': 'سمور',
  'en': 'beaver',
  'ja': 'ビーバー',
  'ko': '비버',
  'uk': 'бобер'},
 'zebra': {'synset_id': 'n02391049',
  'ar': 'الحمار الوحشي',
  'en': 'zebra',
  'ja': 'シマウマ',
  'ko': '얼룩말',
  'uk': 'зебра'},
 'hog': {'synset_id': 'n02395406',
  'ar': 'خنزير',
  'en': 'hog',
  'ja': '豚',
  'ko': '돼지',
  'uk': 'свиня'},
 'hippopotamus': {'synset_id': 'n02398521',
  'ar': 'فرس نهر',
  'en': 'hippopotamus',
  'ja': 'カバ',
  'ko': '하마',
  'uk': 'бегемот'},
 'ox': {'synset_id': 'n02403003',
  'ar': 'ثور',
  'en': 'ox',
  'ja': '牛',
  'ko': '황소',
  'uk': 'віл'},
 'water buffalo': {'synset_id': 'n02408429',
  'ar': 'جاموس الماء',
  'en': 'water buffalo',
  'ja': '水牛',
  'ko': '물소',
  'uk': 'водяний буйвол'},
 'bison': {'synset_id': 'n02410509',
  'ar': 'الثور',
  'en': 'bison',
  'ja': 'バイソン',
  'ko': '바이슨',
  'uk': 'бізон'},
 'ram': {'synset_id': 'n02412080',
  'ar': 'كبش',
  'en': 'ram',
  'ja': 'ラム',
  'ko': '램',
  'uk': 'ОЗП'},
 'otter': {'synset_id': 'n02444819',
  'ar': 'قندس',
  'en': 'otter',
  'ja': 'カワウソ',
  'ko': '수달',
  'uk': 'видра'},
 'skunk': {'synset_id': 'n02445715',
  'ar': 'الظربان',
  'en': 'skunk',
  'ja': 'スカンク',
  'ko': '스컹크',
  'uk': 'скунс'},
 'gorilla': {'synset_id': 'n02480855',
  'ar': 'غوريلا',
  'en': 'gorilla',
  'ja': 'ゴリラ',
  'ko': '고릴라',
  'uk': 'горила'},
 'eel': {'synset_id': 'n02526121',
  'ar': 'الجريث',
  'en': 'eel',
  'ja': 'うなぎ',
  'ko': '뱀장어',
  'uk': 'вугор'},
 'aircraft carrier': {'synset_id': 'n02687172',
  'ar': 'حاملة طائرات',
  'en': 'aircraft carrier',
  'ja': '空母',
  'ko': '항공모함',
  'uk': 'авіаносець'},
 'ambulance': {'synset_id': 'n02701002',
  'ar': 'سياره اسعاف',
  'en': 'ambulance',
  'ja': '救急車',
  'ko': '구급차',
  'uk': 'швидка допомога'},
 'apron': {'synset_id': 'n02730930',
  'ar': 'ساحة',
  'en': 'apron',
  'ja': 'エプロン',
  'ko': '앞치마',
  'uk': 'фартух'},
 'backpack': {'synset_id': 'n02769748',
  'ar': 'حقيبة ظهر',
  'en': 'backpack',
  'ja': 'バックパック',
  'ko': '배낭',
  'uk': 'рюкзак'},
 'bakery': {'synset_id': 'n02776631',
  'ar': 'مخبز',
  'en': 'bakery',
  'ja': 'ベーカリー',
  'ko': '빵집',
  'uk': 'пекарня'},
 'balloon': {'synset_id': 'n02782093',
  'ar': 'بالون',
  'en': 'balloon',
  'ja': 'バルーン',
  'ko': '풍선',
  'uk': 'повітряна куля'},
 'bathtub': {'synset_id': 'n02808440',
  'ar': 'حوض الاستحمام',
  'en': 'bathtub',
  'ja': 'バスタブ',
  'ko': '목욕통',
  'uk': 'ванна'},
 'bucket': {'synset_id': 'n02909870',
  'ar': 'دلو',
  'en': 'bucket',
  'ja': 'バケツ',
  'ko': '버킷',
  'uk': 'відро'}}

In [10]:
pt = "/gpfs/scratch/as16583/symile/src/high_dim/data_reference_50.json"
with open(pt, 'w') as f:
    json.dump(l_dict_50, f, ensure_ascii=False, indent=4)

In [3]:
l_dict

{'tench': {'synset_id': 'n01440764',
  'ar': 'التنش سمك نهري',
  'de': 'Schleie',
  'el': 'είδος κυπρίνου',
  'en': 'tench',
  'es': 'tenca',
  'fr': 'tanche',
  'hi': 'टेंच',
  'id': 'tench',
  'it': 'tinca',
  'ja': 'テンチ',
  'ko': '텐치',
  'nl': 'zeelt',
  'pl': 'lin',
  'pt': 'tenca',
  'ru': 'линь',
  'sv': 'sutare',
  'tr': 'kadife çiçeği',
  'uk': 'линь',
  'vi': 'tench',
  'zh-CN': '丁鳅',
  'cs': 'lín',
  'cy': 'tensio',
  'fi': 'suutari',
  'he': 'טנץ&#39;',
  'hu': 'compó',
  'is': 'seiður',
  'no': 'suter',
  'te': 'టెన్చ్',
  'th': 'เทนช์',
  'ur': 'ٹینچ'},
 'goldfish': {'synset_id': 'n01443537',
  'ar': 'سمكة ذهبية',
  'de': 'Goldfisch',
  'el': 'χρυσόψαρο',
  'en': 'goldfish',
  'es': 'pez de colores',
  'fr': 'poisson rouge',
  'hi': 'ज़र्द मछली',
  'id': 'ikan mas',
  'it': 'pesce rosso',
  'ja': '金魚',
  'ko': '금붕어',
  'nl': 'goudvis',
  'pl': 'złota Rybka',
  'pt': 'peixinho dourado',
  'ru': 'золотая рыбка',
  'sv': 'guldfisk',
  'tr': 'Akvaryum balığı',
  'uk': 'золота рибка',
  'vi': 'cá vàng',
  'zh-CN': '金鱼',
  'cs': 'zlatá rybka',
  'cy': 'pysgodyn aur',
  'fi': 'kultakala',
  'he': 'דג זהב',
  'hu': 'aranyhal',
  'is': 'gullfiskur',
  'no': 'gullfisk',
  'te': 'గోల్డ్ ఫిష్',
  'th': 'ปลาทอง',
  'ur': 'زرد مچھلی'},
 'great white shark': {'synset_id': 'n01484850',
  'ar': 'القرش الابيض الكبير',
  'de': 'großer weißer Hai',
  'el': 'μεγάλος λευκός καρχαρίας',
  'en': 'great white shark',
  'es': 'gran tiburón blanco',
  'fr': 'grand requin blanc',
  'hi': 'विशाल सफेद शार्क',
  'id': 'hiu putih besar',
  'it': 'grande squalo bianco',
  'ja': 'ホホジロザメ',
  'ko': '백상어',
  'nl': 'grote witte haai',
  'pl': 'Wielki biały rekin',
  'pt': 'grande tubarão branco',
  'ru': 'Большая белая акула',
  'sv': 'stor vithaj',
  'tr': 'büyük beyaz köpek balığı',
  'uk': 'велика біла акула',
  'vi': 'cá mập trắng lớn',
  'zh-CN': '大白鲨',
  'cs': 'velký bílý žralok',
  'cy': 'siarc gwyn gwych',
  'fi': 'valkohai',
  'he': 'כריש לבן',
  'hu': 'nagy fehér cápa',
  'is': 'hvíthákarl',
  'no': 'stor hvithai',
  'te': 'గొప్ప తెల్ల సొరచేప',
  'th': 'ฉลามขาว',
  'ur': 'عظیم سفید شارک'},
 'tiger shark': {'synset_id': 'n01491361',
  'ar': 'نمر القرش',
  'de': 'Tigerhai',
  'el': 'καρχαρίας τίγρης',
  'en': 'tiger shark',
  'es': 'tiburón tigre',
  'fr': 'requin tigre',
  'hi': 'टाइगर शार्क',
  'id': 'hiu Macan',
  'it': 'squalo tigre',
  'ja': 'イタチザメ',
  'ko': '범 상어',
  'nl': 'tijgerhaai',
  'pl': 'żarłacz tygrysi',
  'pt': 'Tubarão tigre',
  'ru': 'тигровая акула',
  'sv': 'Tiger haj',
  'tr': 'Kaplan köpek balığı',
  'uk': 'тигрова акула',
  'vi': 'cá mập hổ',
  'zh-CN': '虎鲨',
  'cs': 'žralok tygří',
  'cy': 'siarc teigr',
  'fi': 'tiikerihai',
  'he': 'כריש נמר',
  'hu': 'tigriscápa',
  'is': 'tígrishákarl',
  'no': 'tigerhai',
  'te': 'టైగర్ షార్క్',
  'th': 'ฉลามเสือ',
  'ur': 'ٹائیگر شارک'},
 'hammerhead': {'synset_id': 'n01494475',
  'ar': 'رأس المطرقة',
  'de': 'Hammerkopf',
  'el': 'σφυροκέφαλος',
  'en': 'hammerhead',
  'es': 'tiburón martillo',
  'fr': 'requin-marteau',
  'hi': 'हथौड़ा का सिरा',
  'id': 'kepala martil',
  'it': 'testa di martello',
  'ja': 'シュモクザメ',
  'ko': '귀상어',
  'nl': 'hamerkop',
  'pl': 'młotek',
  'pt': 'tubarão-martelo',
  'ru': 'голова-молот',
  'sv': 'hammarhaj',
  'tr': 'çekiç kafalı',
  'uk': 'головка молотка',
  'vi': 'đầu búa',
  'zh-CN': '锤头鲨',
  'cs': 'kladivoun',
  'cy': 'pen morthwyl',
  'fi': 'vasarapää',
  'he': 'פַּטִישׁ הַיָם',
  'hu': 'kalapácsfej',
  'is': 'hamarhaus',
  'no': 'hammerhode',
  'te': 'సుత్తి తల',
  'th': 'แฮมเมอร์เฮด',
  'ur': 'ہتھوڑا'},
 'electric ray': {'synset_id': 'n01496331',
  'ar': 'شعاع كهربائي',
  'de': 'Zitterrochen',
  'el': 'ηλεκτρική ακτίνα',
  'en': 'electric ray',
  'es': 'rayo electrico',
  'fr': 'rayon électrique',
  'hi': 'विद्युत किरण',
  'id': 'sinar listrik',
  'it': 'raggio elettrico',
  'ja': '電気線',
  'ko': '전기 광선',
  'nl': 'elektrische straal',
  'pl': 'promień elektryczny',
  'pt': 'raio elétrico',
  'ru': 'электрический скат',
  'sv': 'elektrisk stråle',
  'tr': 'elektrik ışını',
  'uk': 'електричний промінь',
  'vi': 'tia điện',
  'zh-CN': '电射线',
  'cs': 'elektrický paprsek',
  'cy': 'pelydr trydan',
  'fi': 'sähköinen säde',
  'he': 'קרן חשמלית',
  'hu': 'elektromos sugár',
  'is': 'rafgeisli',
  'no': 'elektrisk stråle',
  'te': 'విద్యుత్ కిరణం',
  'th': 'รังสีไฟฟ้า',
  'ur': 'برقی شعاع'},
 'stingray': {'synset_id': 'n01498041',
  'ar': 'اللادغة',
  'de': 'Stachelrochen',
  'el': 'σαλάχι',
  'en': 'stingray',
  'es': 'mantarraya',
  'fr': 'Raie',
  'hi': 'Stingray के',
  'id': 'ikan pari',
  'it': 'pastinaca',
  'ja': 'アカエイ',
  'ko': '가오리',
  'nl': 'pijlstaartrog',
  'pl': 'płaszczka',
  'pt': 'arraia',
  'ru': 'морской скат',
  'sv': 'stingrocka',
  'tr': 'vatoz',
  'uk': 'скат',
  'vi': 'cá đuối gai độc',
  'zh-CN': '黄貂鱼',
  'cs': 'rejnok',
  'cy': 'stingray',
  'fi': 'keihäsrausku',
  'he': 'טריגון',
  'hu': 'rája',
  'is': 'stingreykja',
  'no': 'rokke',
  'te': 'స్టింగ్రే',
  'th': 'ปลากระเบน',
  'ur': 'stingray'},
 'cock': {'synset_id': 'n01514668',
  'ar': 'الديك',
  'de': 'Schwanz',
  'el': 'κόκορας',
  'en': 'cock',
  'es': 'polla',
  'fr': 'coq',
  'hi': 'मुर्गा',
  'id': 'kokang',
  'it': 'cazzo',
  'ja': 'コック',
  'ko': '수탉',
  'nl': 'pik',
  'pl': 'kogut',
  'pt': 'galo',
  'ru': 'петух',
  'sv': 'kuk',
  'tr': 'horoz',
  'uk': 'півень',
  'vi': 'gà trống',
  'zh-CN': '公鸡',
  'cs': 'kohout',
  'cy': 'ceiliog',
  'fi': 'kukko',
  'he': 'תַרְנְגוֹל',
  'hu': 'kakas',
  'is': 'hani',
  'no': 'kuk',
  'te': 'ఆత్మవిశ్వాసం',
  'th': 'ไก่',
  'ur': 'مرگا'},
 'hen': {'synset_id': 'n01514859',
  'ar': 'دجاجة',
  'de': 'Henne',
  'el': 'κότα',
  'en': 'hen',
  'es': 'gallina',
  'fr': 'poule',
  'hi': 'ब',
  'id': 'induk ayam',
  'it': 'gallina',
  'ja': '鶏',
  'ko': '암탉',
  'nl': 'kip',
  'pl': 'kura',
  'pt': 'galinha',
  'ru': 'курица',
  'sv': 'höna',
  'tr': 'tavuk',
  'uk': 'курка',
  'vi': 'con gà mái',
  'zh-CN': '母鸡',
  'cs': 'slepice',
  'cy': 'iâr',
  'fi': 'kana',
  'he': 'תַרְנְגוֹלֶת',
  'hu': 'tyúk',
  'is': 'hæna',
  'no': 'høne',
  'te': 'కోడి',
  'th': 'ไก่',
  'ur': 'مرغی'},
 'ostrich': {'synset_id': 'n01518878',
  'ar': 'نعامة',
  'de': 'Strauß',
  'el': 'στρουθοκάμηλος',
  'en': 'ostrich',
  'es': 'avestruz',
  'fr': 'autruche',
  'hi': 'शुतुरमुर्ग',
  'id': 'burung unta',
  'it': 'struzzo',
  'ja': 'ダチョウ',
  'ko': '타조',
  'nl': 'struisvogel',
  'pl': 'struś',
  'pt': 'avestruz',
  'ru': 'страус',
  'sv': 'struts',
  'tr': 'devekuşu',
  'uk': 'страус',
  'vi': 'đà điểu',
  'zh-CN': '鸵鸟',
  'cs': 'pštros',
  'cy': 'estrys',
  'fi': 'strutsi',
  'he': 'יען',
  'hu': 'strucc',
  'is': 'strútur',
  'no': 'struts',
  'te': 'ఉష్ట్రపక్షి',
  'th': 'นกกระจอกเทศ',
  'ur': 'شترمرغ'},
 'brambling': {'synset_id': 'n01530575',
  'ar': 'التلعثم',
  'de': 'murmelnd',
  'el': 'τσαχπινιά',
  'en': 'brambling',
  'es': 'pinzón',
  'fr': 'ronces',
  'hi': 'बड़बड़ाना',
  'id': 'semak duri',
  'it': 'Peppola',
  'ja': 'いばら',
  'ko': '불평',
  'nl': 'bramen',
  'pl': 'brambling',
  'pt': 'amontoado',
  'ru': 'юрок',
  'sv': 'bramlande',
  'tr': 'dalavere',
  'uk': 'ожина',
  'vi': 'bụi gai',
  'zh-CN': '布兰布林',
  'cs': 'brambling',
  'cy': 'mieri',
  'fi': 'bramling',
  'he': 'ברוגז',
  'hu': 'dörzsölés',
  'is': 'bruðl',
  'no': 'bramling',
  'te': 'మురిసిపోవడం',
  'th': 'การดิ้นรน',
  'ur': 'brambling'},
 'goldfinch': {'synset_id': 'n01531178',
  'ar': 'طائر الحسون',
  'de': 'Stieglitz',
  'el': 'καρδερίνα',
  'en': 'goldfinch',
  'es': 'jilguero',
  'fr': 'chardonneret',
  'hi': 'सोने का सिक्का',
  'id': 'uang emas',
  'it': 'cardellino',
  'ja': 'ゴシキヒワ',
  'ko': '금화',
  'nl': 'distelvink',
  'pl': 'szczygieł',
  'pt': 'pintassilgo',
  'ru': 'щегол',
  'sv': 'steglits',
  'tr': 'saka kuşu',
  'uk': 'щиголь',
  'vi': 'chim kim oanh',
  'zh-CN': '金翅雀',
  'cs': 'stehlík',
  'cy': 'llinos eurben',
  'fi': 'kultavarppu',
  'he': 'חוֹחִית',
  'hu': 'tengelice',
  'is': 'gullfinka',
  'no': 'gullfink',
  'te': 'గోల్డ్ ఫించ్',
  'th': 'โกลด์ฟินช์',
  'ur': 'گولڈ فنچ'},
 'house finch': {'synset_id': 'n01532829',
  'ar': 'عصفور المنزل',
  'de': 'Hausfink',
  'el': 'σπίνι του σπιτιού',
  'en': 'house finch',
  'es': 'pinzón doméstico',
  'fr': 'pinson domestique',
  'hi': 'हाउस फिंच',
  'id': 'burung kutilang rumah',
  'it': 'fringuello domestico',
  'ja': 'イエフィンチ',
  'ko': '집 핀치',
  'nl': 'huis vink',
  'pl': 'zięba domowa',
  'pt': 'tentilhão doméstico',
  'ru': 'домашний зяблик',
  'sv': 'bofink',
  'tr': 'ev ispinozu',
  'uk': 'домашній зяблик',
  'vi': 'chim sẻ nhà',
  'zh-CN': '家雀',
  'cs': 'pěnkava domácí',
  'cy': 'llinos y ty',
  'fi': 'talon peippo',
  'he': 'חוחיית הבית',
  'hu': 'házi pinty',
  'is': 'húsfinka',
  'no': 'husfink',
  'te': 'ఇంటి ఫించ్',
  'th': 'นกกระจิบบ้าน',
  'ur': 'گھر فنچ'},
 'junco': {'synset_id': 'n01534433',
  'ar': 'يسرع',
  'de': 'eilen',
  'el': 'βιασύνη',
  'en': 'junco',
  'es': 'junco',
  'fr': 'se précipiter',
  'hi': 'जल्दबाज़ी करना',
  'id': 'bergegas',
  'it': 'fretta',
  'ja': '急ぐ',
  'ko': '서두르다',
  'nl': 'haast',
  'pl': 'pośpiech',
  'pt': 'Junco',
  'ru': 'торопиться',
  'sv': 'rusa',
  'tr': 'acele etmek',
  'uk': 'поспіх',
  'vi': 'cây bấc',
  'zh-CN': '匆忙',
  'cs': 'spěch',
  'cy': 'rhuthr',
  'fi': 'kiire',
  'he': 'לְמַהֵר',
  'hu': 'rohanás',
  'is': 'þjóta',
  'no': 'skynde',
  'te': 'హడావిడి',
  'th': 'รีบ',
  'ur': 'جلدی'},
 'indigo bunting': {'synset_id': 'n01537544',
  'ar': 'الرايات النيلية',
  'de': 'Indigo-Ammer',
  'el': 'indigo bunting',
  'en': 'indigo bunting',
  'es': 'empavesado índigo',
  'fr': 'bruant indigo',
  'hi': 'इंडिगो बंटिंग',
  'id': 'bendera nila',
  'it': 'stamina indaco',
  'ja': 'インディゴホオジロ',
  'ko': '인디고 깃발',
  'nl': 'indigo vlaggetjes',
  'pl': 'chorągiewka w kolorze indygo',
  'pt': 'bandeira índigo',
  'ru': 'овсянка цвета индиго',
  'sv': 'indigo bunting',
  'tr': 'çivit kiraz kuşu',
  'uk': 'вівсянка індиго',
  'vi': 'cờ đuôi nheo màu chàm',
  'zh-CN': '靛蓝彩旗',
  'cs': 'strnad indigový',
  'cy': 'bunting indigo',
  'fi': 'indigo-sirkku',
  'he': 'גפת אינדיגו',
  'hu': 'indigó sármány',
  'is': 'indigo bunting',
  'no': 'indigo-spurv',
  'te': 'నీలిమందు బంటింగ్',
  'th': 'ตอม่อสีคราม',
  'ur': 'انڈگو بنٹنگ'},
 'robin': {'synset_id': 'n01558993',
  'ar': 'روبن',
  'de': 'Rotkehlchen',
  'el': 'κοκκινολαίμης',
  'en': 'robin',
  'es': 'petirrojo',
  'fr': 'rouge-gorge',
  'hi': 'रोबिन',
  'id': 'robin',
  'it': 'pettirosso',
  'ja': 'ロビン',
  'ko': '남자 이름',
  'nl': 'roodborstje',
  'pl': 'rudzik',
  'pt': 'robin',
  'ru': 'Робин',
  'sv': 'robin',
  'tr': 'ardıç kuşu',
  'uk': 'малиновка',
  'vi': 'chim cổ đỏ',
  'zh-CN': '知更鸟',
  'cs': 'červenka',
  'cy': 'robin',
  'fi': 'robin',
  'he': 'אָדוֹם הַחֲזֶה',
  'hu': 'vörösbegy',
  'is': 'Robin',
  'no': 'robin',
  'te': 'రాబిన్',
  'th': 'โรบิน',
  'ur': 'رابن'},
 'bulbul': {'synset_id': 'n01560419',
  'ar': 'بلبل',
  'de': 'Bulbul',
  'el': 'πουλί bulbul',
  'en': 'bulbul',
  'es': 'bulbul',
  'fr': 'bulbul',
  'hi': 'बुलबुल',
  'id': 'bulbul',
  'it': 'bulbul',
  'ja': 'ヒヨドリ',
  'ko': '벌불',
  'nl': 'bulbul',
  'pl': 'Bulbul',
  'pt': 'bulbul',
  'ru': 'луковица',
  'sv': 'bulbul',
  'tr': 'bülbül',
  'uk': 'птах бюльбюль',
  'vi': 'chào mào',
  'zh-CN': '鹎',
  'cs': 'bulbul',
  'cy': 'bwbwl',
  'fi': 'bulbul',
  'he': 'בּוּלְבּוּל',
  'hu': 'bulbul',
  'is': 'bulbul',
  'no': 'bulbul',
  'te': 'బుల్బుల్',
  'th': 'นกปรอด',
  'ur': 'بلبل پرندہ'},
 'jay': {'synset_id': 'n01580077',
  'ar': 'جاي',
  'de': 'Jay',
  'el': 'κίσσα',
  'en': 'jay',
  'es': 'arrendajo',
  'fr': 'geai',
  'hi': 'नीलकंठ',
  'id': 'jay',
  'it': 'ghiandaia',
  'ja': 'ジェイ',
  'ko': '어치',
  'nl': 'gaai',
  'pl': 'sójka',
  'pt': 'gaio',
  'ru': 'Джей',
  'sv': 'jay',
  'tr': 'alakarga',
  'uk': 'сойка',
  'vi': 'chim giẻ cùi',
  'zh-CN': '杰伊',
  'cs': 'sojka',
  'cy': 'sgrech y coed',
  'fi': 'jay',
  'he': 'עוֹרְבָנִי',
  'hu': 'szajkó',
  'is': 'jay',
  'no': 'jay',
  'te': 'జై',
  'th': 'เจย์',
  'ur': 'جے'},
 'magpie': {'synset_id': 'n01582220',
  'ar': 'العقعق',
  'de': 'Elster',
  'el': 'καρακάξα',
  'en': 'magpie',
  'es': 'urraca',
  'fr': 'pie',
  'hi': 'अधेला',
  'id': 'murai',
  'it': 'gazza',
  'ja': 'カササギ',
  'ko': '까치',
  'nl': 'ekster',
  'pl': 'sroka',
  'pt': 'pega',
  'ru': 'сорока',
  'sv': 'skata',
  'tr': 'saksağan',
  'uk': 'сорока',
  'vi': 'chim ác là',
  'zh-CN': '鹊',
  'cs': 'straka',
  'cy': 'pigyn',
  'fi': 'harakka',
  'he': 'עוֹרֵב הַנְחָלִים',
  'hu': 'szarka',
  'is': 'skauta',
  'no': 'skjære',
  'te': 'మాగ్పీ',
  'th': 'นกกางเขน',
  'ur': 'میگپی'},
 'chickadee': {'synset_id': 'n01592084',
  'ar': 'طائر القرقف',
  'de': 'Meise',
  'el': 'είδος αιγίθαλου',
  'en': 'chickadee',
  'es': 'paro',
  'fr': 'mésange',
  'hi': 'चिकैडी',
  'id': 'cewek',
  'it': 'cinciallegra',
  'ja': 'コガラ',
  'ko': '총칭',
  'nl': 'mees',
  'pl': 'sikorka',
  'pt': 'chapim',
  'ru': 'синица',
  'sv': 'chickadee',
  'tr': 'bülbül',
  'uk': 'синиця',
  'vi': 'con gà trống',
  'zh-CN': '山雀',
  'cs': 'americký ptáček',
  'cy': 'cyw',
  'fi': 'kananpoika',
  'he': 'צ&#39;יקדי',
  'hu': 'feketefejű cinke',
  'is': 'kjúklingur',
  'no': 'chickadee',
  'te': 'చికాడీ',
  'th': 'เจี๊ยบ',
  'ur': 'چکڈی'},
 'water ouzel': {'synset_id': 'n01601694',
  'ar': 'أوزيل الماء',
  'de': 'Wasser Ouzel',
  'el': 'ουζέλι νερού',
  'en': 'water ouzel',
  'es': 'miga de agua',
  'fr': 'eau ouzel',
  'hi': 'पानी उज़ेल',
  'id': 'cairan air',
  'it': 'merlo d&#39;acqua',
  'ja': 'ウォーターウゼル',
  'ko': '물 우젤',
  'nl': 'water ouzel',
  'pl': 'ouzel wodny',
  'pt': 'ouzel de água',
  'ru': 'водная узель',
  'sv': 'vattenouzel',
  'tr': 'su uzeli',
  'uk': 'вода ouzel',
  'vi': 'nước suối',
  'zh-CN': '水乌泽尔',
  'cs': 'vodní ouzel',
  'cy': 'mwyalchen dwr',
  'fi': 'vesi ouzel',
  'he': 'אוזל מים',
  'hu': 'víz ouzel',
  'is': 'vatnsdrykkja',
  'no': 'vann ouzel',
  'te': 'నీటి ఔజెల్',
  'th': 'น้ำอูเซล',
  'ur': 'پانی ouzel'},
 'kite': {'synset_id': 'n01608432',
  'ar': 'يرى',
  'de': 'sehen',
  'el': 'βλέπω',
  'en': 'kite',
  'es': 'ver',
  'fr': 'voir',
  'hi': 'देखना',
  'id': 'melihat',
  'it': 'Vedere',
  'ja': '見る',
  'ko': '보다',
  'nl': 'zien',
  'pl': 'Widzieć',
  'pt': 'ver',
  'ru': 'видеть',
  'sv': 'ser',
  'tr': 'Görmek',
  'uk': 'побачити',
  'vi': 'nhìn thấy',
  'zh-CN': '看',
  'cs': 'vidět',
  'cy': 'gw',
  'fi': 'katso',
  'he': 'לִרְאוֹת',
  'hu': 'lát',
  'is': 'sjáðu',
  'no': 'se',
  'te': 'చూడండి',
  'th': 'ดู',
  'ur': 'دیکھیں'},
 'bald eagle': {'synset_id': 'n01614925',
  'ar': 'النسر الأصلع',
  'de': 'Weißkopfseeadler',
  'el': 'φαλακρός αετός',
  'en': 'bald eagle',
  'es': 'Águila calva',
  'fr': 'Pygargue à tête blanche',
  'hi': 'गंजा ईगल',
  'id': 'Elang botak',
  'it': 'aquila calva',
  'ja': '白頭ワシ',
  'ko': '대머리 독수리',
  'nl': 'kale adelaar',
  'pl': 'bielik',
  'pt': 'Águia careca',
  'ru': 'белоголовый орлан',
  'sv': 'vithövdad havsörn',
  'tr': 'kel kartal',
  'uk': 'Білоголовий орлан',
  'vi': 'đại bàng hói',
  'zh-CN': '白头鹰',
  'cs': 'Orel bělohlavý',
  'cy': 'eryr moel',
  'fi': 'kalju kotka',
  'he': 'נשר קירח',
  'hu': 'kopasz sas',
  'is': 'Skallaörn',
  'no': 'skallet ørn',
  'te': 'బట్టతల డేగ',
  'th': 'นกอินทรีหัวล้าน',
  'ur': 'گنجا عقاب'},
 'vulture': {'synset_id': 'n01616318',
  'ar': 'نسر',
  'de': 'Geier',
  'el': 'όρνιο',
  'en': 'vulture',
  'es': 'buitre',
  'fr': 'vautour',
  'hi': 'गिद्ध',
  'id': 'burung bangkai',
  'it': 'avvoltoio',
  'ja': 'ハゲワシ',
  'ko': '무자비한 사람',
  'nl': 'gier',
  'pl': 'sęp',
  'pt': 'abutre',
  'ru': 'стервятник',
  'sv': 'gam',
  'tr': 'akbaba',
  'uk': 'гриф',
  'vi': 'con kền kền',
  'zh-CN': '秃鹫',
  'cs': 'sup',
  'cy': 'fwltur',
  'fi': 'korppikotka',
  'he': 'עיט',
  'hu': 'keselyű',
  'is': 'geirfugl',
  'no': 'gribb',
  'te': 'రాబందు',
  'th': 'อีแร้ง',
  'ur': 'گدھ'},
 'great grey owl': {'synset_id': 'n01622779',
  'ar': 'البومة الرمادية العظيمة',
  'de': 'Bartkauz',
  'el': 'μεγάλη γκρίζα κουκουβάγια',
  'en': 'great grey owl',
  'es': 'gran búho gris',
  'fr': 'chouette lapone',
  'hi': 'महान ग्रे उल्लू',
  'id': 'burung hantu abu-abu besar',
  'it': 'grande gufo grigio',
  'ja': '大きな灰色のフクロウ',
  'ko': '큰 회색 올빼미',
  'nl': 'grote grijze uil',
  'pl': 'wielka szara sowa',
  'pt': 'grande coruja cinzenta',
  'ru': 'большая серая сова',
  'sv': 'stor grå uggla',
  'tr': 'büyük gri baykuş',
  'uk': 'велика сіра сова',
  'vi': 'cú xám lớn',
  'zh-CN': '大灰猫头鹰',
  'cs': 'velká šedá sova',
  'cy': 'tylluan lwyd fawr',
  'fi': 'suuri harmaa pöllö',
  'he': 'ינשוף אפור גדול',
  'hu': 'nagy szürke bagoly',
  'is': 'mikil grá ugla',
  'no': 'stor grå ugle',
  'te': 'గొప్ప బూడిద గుడ్లగూబ',
  'th': 'นกฮูกสีเทาที่ยิ่งใหญ่',
  'ur': 'عظیم سرمئی اللو'},
 'European fire salamander': {'synset_id': 'n01629819',
  'ar': 'السمندل الناري الأوروبي',
  'de': 'Europäischer Feuersalamander',
  'el': 'Ευρωπαϊκή φωτιά σαλαμάνδρα',
  'en': 'European fire salamander',
  'es': 'salamandra europea',
  'fr': 'Salamandre de feu européenne',
  'hi': 'यूरोपीय अग्नि समन्दर',
  'id': 'Salamander api Eropa',
  'it': 'Salamandra pezzata europea',
  'ja': 'ヨーロッパファイアサラマンダー',
  'ko': '유럽의 불 도롱뇽',
  'nl': 'Europese vuursalamander',
  'pl': 'Europejska salamandra plamista',
  'pt': 'Salamandra de fogo europeia',
  'ru': 'Европейская огненная саламандра',
  'sv': 'Europeisk eldsalamander',
  'tr': 'Avrupa ateş semenderi',
  'uk': 'Європейська вогняна саламандра',
  'vi': 'Kỳ giông lửa châu Âu',
  'zh-CN': '欧洲火蝾螈',
  'cs': 'Evropský mlok ohnivý',
  'cy': 'salamander tân Ewropeaidd',
  'fi': 'Eurooppalainen tulisalamanteri',
  'he': 'סלמנדרת אש אירופאית',
  'hu': 'Európai tűzszalamandra',
  'is': 'Evrópsk eldsalamandra',
  'no': 'Europeisk brannsalamander',
  'te': 'యూరోపియన్ అగ్ని సాలమండర్',
  'th': 'ซาลาแมนเดอร์ไฟยุโรป',
  'ur': 'یورپی فائر سلامینڈر'},
 'common newt': {'synset_id': 'n01630670',
  'ar': 'نيوت مشترك',
  'de': 'Gemeiner Molch',
  'el': 'κοινός τρίτωνας',
  'en': 'common newt',
  'es': 'tritón común',
  'fr': 'triton commun',
  'hi': 'सामान्य न्यूट',
  'id': 'kadal air biasa',
  'it': 'tritone comune',
  'ja': 'イモリ',
  'ko': '일반적인 영원',
  'nl': 'gewone newt',
  'pl': 'traszka zwyczajna',
  'pt': 'tritão comum',
  'ru': 'обыкновенный тритон',
  'sv': 'vanlig vattensalamander',
  'tr': 'ortak semender',
  'uk': 'звичайний тритон',
  'vi': 'sa giông thông thường',
  'zh-CN': '蝾螈',
  'cs': 'čolek obecný',
  'cy': 'madfall gyffredin',
  'fi': 'tavallinen newt',
  'he': 'ניוט מצוי',
  'hu': 'közönséges gőte',
  'is': 'algeng salamala',
  'no': 'vanlig salamander',
  'te': 'సాధారణ న్యూట్',
  'th': 'นิวท์สามัญ',
  'ur': 'عام نیوٹ'},
 'eft': {'synset_id': 'n01631663',
  'ar': 'إنها',
  'de': 'es ist',
  'el': 'είναι',
  'en': 'eft',
  'es': 'es',
  'fr': 'c&#39;est',
  'hi': 'यह है',
  'id': 'dia',
  'it': 'è',
  'ja': 'それはです',
  'ko': '그것은',
  'nl': 'het is',
  'pl': 'to jest',
  'pt': 'isso é',
  'ru': 'это',
  'sv': 'det är',
  'tr': 'bu',
  'uk': 'Це є',
  'vi': 'nó là',
  'zh-CN': '这是',
  'cs': 'to je',
  'cy': 'Mae&#39;n',
  'fi': 'se on',
  'he': 'זה',
  'hu': 'ez',
  'is': 'það er',
  'no': 'Det er',
  'te': 'అది',
  'th': 'มันคือ',
  'ur': 'یہ ہے'},
 'spotted salamander': {'synset_id': 'n01632458',
  'ar': 'السمندل المرقط',
  'de': 'gefleckter Salamander',
  'el': 'στικτές σαλαμάνδρα',
  'en': 'spotted salamander',
  'es': 'salamandra manchada',
  'fr': 'salamandre maculée',
  'hi': 'चित्तीदार सैलामैंडर',
  'id': 'salamander tutul',
  'it': 'salamandra pezzata',
  'ja': 'マダラサンショウウオ',
  'ko': '점박이 도롱뇽',
  'nl': 'gevlekte salamander',
  'pl': 'salamandra plamista',
  'pt': 'salamandra manchada',
  'ru': 'пятнистая саламандра',
  'sv': 'fläckig salamander',
  'tr': 'benekli semender',
  'uk': 'плямиста саламандра',
  'vi': 'kỳ nhông đốm',
  'zh-CN': '斑点蝾螈',
  'cs': 'salamandr skvrnitý',
  'cy': 'salamander smotiog',
  'fi': 'täplikäs salamanteri',
  'he': 'סלמנדרה מנומרת',
  'hu': 'foltos szalamandra',
  'is': 'flekkótt salamander',
  'no': 'flekket salamander',
  'te': 'మచ్చల సాలమండర్',
  'th': 'ซาลาแมนเดอร์ด่าง',
  'ur': 'داغدار سلامینڈر'},
 'axolotl': {'synset_id': 'n01632777',
  'ar': 'قنفذ البحر',

In [6]:
l_dict['tench']

{'synset_id': 'n01440764',
 'ar': 'التنش سمك نهري',
 'de': 'Schleie',
 'el': 'είδος κυπρίνου',
 'en': 'tench',
 'es': 'tenca',
 'fr': 'tanche',
 'hi': 'टेंच',
 'id': 'tench',
 'it': 'tinca',
 'ja': 'テンチ',
 'ko': '텐치',
 'nl': 'zeelt',
 'pl': 'lin',
 'pt': 'tenca',
 'ru': 'линь',
 'sv': 'sutare',
 'tr': 'kadife çiçeği',
 'uk': 'линь',
 'vi': 'tench',
 'zh-CN': '丁鳅',
 'cs': 'lín',
 'cy': 'tensio',
 'fi': 'suutari',
 'he': 'טנץ&#39;',
 'hu': 'compó',
 'is': 'seiður',
 'no': 'suter',
 'te': 'టెన్చ్',
 'th': 'เทนช์',
 'ur': 'ٹینچ',
 'cls_id': 0}

In [4]:
# Add "cls_id" to each animal key with a unique number
for index, (cls, properties) in enumerate(l_dict.items()):
    properties["cls_id"] = index

In [7]:
# pt = "/gpfs/scratch/as16583/symile/src/high_dim/data_reference_50.json"
with open(pt, 'w') as f:
    json.dump(l_dict, f, ensure_ascii=False, indent=4)

In [41]:
pt = "/gpfs/scratch/as16583/symile/src/high_dim/data/t2/disjoint/train.csv"
df = pd.read_csv(pt)

In [42]:
df['image_filename'] = df.image_path.apply(lambda x: x.split('/')[-1].split('.')[0])

In [43]:
df.to_csv(pt, index=False)

In [ ]:
print(df.iloc[1].image_path)
print(df.iloc[1].image_filename)