In [26]:
import pandas as pd

In [27]:
df = pd.read_csv("tuning_runs.csv")

In [28]:
df

,run_name,loss_fn,ckpt_pt,epoch,val_loss,val_accuracy,weight_decay,learning_rate,wandb_path
0,20240420_234318_0568,symile,/gpfs/scratch/as16583/ckpts/high_dim/20240420_...,1,0.895415,0.918768,0.000,0.00010,https://wandb.ai/rajesh-lab/symile/runs/7kt5ce2v
1,20240420_234318_0568,symile,/gpfs/scratch/as16583/ckpts/high_dim/20240420_...,3,0.836875,0.924216,0.000,0.00010,https://wandb.ai/rajesh-lab/symile/runs/7kt5ce2v
2,20240420_234318_0568,symile,/gpfs/scratch/as16583/ckpts/high_dim/20240420_...,5,0.814676,0.927872,0.000,0.00010,https://wandb.ai/rajesh-lab/symile/runs/7kt5ce2v
3,20240420_234318_0568,symile,/gpfs/scratch/as16583/ckpts/high_dim/20240420_...,7,0.798005,0.925732,0.000,0.00010,https://wandb.ai/rajesh-lab/symile/runs/7kt5ce2v
4,20240420_234318_0568,symile,/gpfs/scratch/as16583/ckpts/high_dim/20240420_...,9,0.784555,0.925992,0.000,0.00010,https://wandb.ai/rajesh-lab/symile/runs/7kt5ce2v
...,...,...,...,...,...,...,...,...,...
211,20240423_115936_9838,clip,/gpfs/scratch/as16583/ckpts/high_dim/20240423_...,15,11.831726,0.474434,0.001,0.00001,https://wandb.ai/rajesh-lab/symile/runs/bihyyevy
212,20240423_115936_9838,clip,/gpfs/scratch/as16583/ckpts/high_dim/20240423_...,17,11.828800,0.474986,0.001,0.00001,https://wandb.ai/rajesh-lab/symile/runs/bihyyevy
213,20240423_115936_9838,clip,/gpfs/scratch/as16583/ckpts/high_dim/20240423_...,19,11.828110,0.475228,0.001,0.00001,https://wandb.ai/rajesh-lab/symile/runs/bihyyevy
214,20240423_115936_9838,clip,/gpfs/scratch/as16583/ckpts/high_dim/20240423_...,21,11.827398,0.475884,0.001,0.00001,https://wandb.ai/rajesh-lab/symile/runs/bihyyevy
215,20240423_115936_9838,clip,/gpfs/scratch/as16583/ckpts/high_dim/20240423_...,23,11.828797,0.475136,0.001,0.00001,https://wandb.ai/rajesh-lab/symile/runs/bihyyevy

In [29]:
symile_df = df[df["loss_fn"] == "symile"]
clip_df = df[df["loss_fn"] == "clip"]

## symile

In [30]:
symile_df

,run_name,loss_fn,ckpt_pt,epoch,val_loss,val_accuracy,weight_decay,learning_rate,wandb_path
0,20240420_234318_0568,symile,/gpfs/scratch/as16583/ckpts/high_dim/20240420_...,1,0.895415,0.918768,0.000,0.00010,https://wandb.ai/rajesh-lab/symile/runs/7kt5ce2v
1,20240420_234318_0568,symile,/gpfs/scratch/as16583/ckpts/high_dim/20240420_...,3,0.836875,0.924216,0.000,0.00010,https://wandb.ai/rajesh-lab/symile/runs/7kt5ce2v
2,20240420_234318_0568,symile,/gpfs/scratch/as16583/ckpts/high_dim/20240420_...,5,0.814676,0.927872,0.000,0.00010,https://wandb.ai/rajesh-lab/symile/runs/7kt5ce2v
3,20240420_234318_0568,symile,/gpfs/scratch/as16583/ckpts/high_dim/20240420_...,7,0.798005,0.925732,0.000,0.00010,https://wandb.ai/rajesh-lab/symile/runs/7kt5ce2v
4,20240420_234318_0568,symile,/gpfs/scratch/as16583/ckpts/high_dim/20240420_...,9,0.784555,0.925992,0.000,0.00010,https://wandb.ai/rajesh-lab/symile/runs/7kt5ce2v
...,...,...,...,...,...,...,...,...,...
103,20240421_232822_1628,symile,/gpfs/scratch/as16583/ckpts/high_dim/20240421_...,15,0.759142,0.941840,0.001,0.00001,https://wandb.ai/rajesh-lab/symile/runs/ia87ymgb
104,20240421_232822_1628,symile,/gpfs/scratch/as16583/ckpts/high_dim/20240421_...,17,0.753677,0.939136,0.001,0.00001,https://wandb.ai/rajesh-lab/symile/runs/ia87ymgb
105,20240421_232822_1628,symile,/gpfs/scratch/as16583/ckpts/high_dim/20240421_...,19,0.745658,0.936614,0.001,0.00001,https://wandb.ai/rajesh-lab/symile/runs/ia87ymgb
106,20240421_232822_1628,symile,/gpfs/scratch/as16583/ckpts/high_dim/20240421_...,21,0.744802,0.940138,0.001,0.00001,https://wandb.ai/rajesh-lab/symile/runs/ia87ymgb
107,20240421_232822_1628,symile,/gpfs/scratch/as16583/ckpts/high_dim/20240421_...,23,0.738397,0.940542,0.001,0.00001,https://wandb.ai/rajesh-lab/symile/runs/ia87ymgb

In [35]:
# VAL LOSS, ASCENDING TRUE
symile_df.sort_values(by="val_loss", ascending=True).head(3)

,run_name,loss_fn,ckpt_pt,epoch,val_loss,val_accuracy,weight_decay,learning_rate,wandb_path
107,20240421_232822_1628,symile,/gpfs/scratch/as16583/ckpts/high_dim/20240421_...,23,0.738397,0.940542,0.0010,0.00001,https://wandb.ai/rajesh-lab/symile/runs/ia87ymgb
35,20240420_234318_7972,symile,/gpfs/scratch/as16583/ckpts/high_dim/20240420_...,23,0.738397,0.940542,0.0000,0.00001,https://wandb.ai/rajesh-lab/symile/runs/eheyszc4
71,20240420_234418_5021,symile,/gpfs/scratch/as16583/ckpts/high_dim/20240420_...,23,0.738397,0.940542,0.0001,0.00001,https://wandb.ai/rajesh-lab/symile/runs/gpv9rday

In [38]:
# VAL ACC AT 1, ASCENDING FALSE
symile_df.sort_values(by="val_accuracy", ascending=False).head(3)

,run_name,loss_fn,ckpt_pt,epoch,val_loss,val_accuracy,weight_decay,learning_rate,wandb_path
67,20240420_234418_5021,symile,/gpfs/scratch/as16583/ckpts/high_dim/20240420_...,15,0.759142,0.94184,0.0001,0.00001,https://wandb.ai/rajesh-lab/symile/runs/gpv9rday
103,20240421_232822_1628,symile,/gpfs/scratch/as16583/ckpts/high_dim/20240421_...,15,0.759142,0.94184,0.0010,0.00001,https://wandb.ai/rajesh-lab/symile/runs/ia87ymgb
31,20240420_234318_7972,symile,/gpfs/scratch/as16583/ckpts/high_dim/20240420_...,15,0.759142,0.94184,0.0000,0.00001,https://wandb.ai/rajesh-lab/symile/runs/eheyszc4

## clip

clip_df

In [42]:
# VAL LOSS, ASCENDING TRUE
clip_df.sort_values(by="val_loss", ascending=True).head(1)

,run_name,loss_fn,ckpt_pt,epoch,val_loss,val_accuracy,weight_decay,learning_rate,wandb_path
118,20240422_113547_4506,clip,/gpfs/scratch/as16583/ckpts/high_dim/20240422_...,21,11.804806,0.474352,0.0,0.0001,https://wandb.ai/rajesh-lab/symile/runs/xkg77rbv

In [49]:
# VAL ACC AT 1, ASCENDING FALSE
clip_df.sort_values(by="val_accuracy", ascending=False).head(3)

,run_name,loss_fn,ckpt_pt,epoch,val_loss,val_accuracy,weight_decay,learning_rate,wandb_path
214,20240423_115936_9838,clip,/gpfs/scratch/as16583/ckpts/high_dim/20240423_...,21,11.827398,0.475884,0.0010,0.00001,https://wandb.ai/rajesh-lab/symile/runs/bihyyevy
178,20240422_230041_4123,clip,/gpfs/scratch/as16583/ckpts/high_dim/20240422_...,21,11.827398,0.475884,0.0001,0.00001,https://wandb.ai/rajesh-lab/symile/runs/plixkmla
142,20240422_113618_9164,clip,/gpfs/scratch/as16583/ckpts/high_dim/20240422_...,21,11.827398,0.475884,0.0000,0.00001,https://wandb.ai/rajesh-lab/symile/runs/ebnfy1x5