In [1]:
import pandas as pd

In [5]:
pd.set_option('display.max_colwidth', None)

df = pd.read_csv("tuning_runs.csv")

df = df[df['pretrained'] == False]
df = df[df['loss_fn'] != 'symile']

len(df)

8000

In [3]:
col_to_keep = ['loss_fn', 'pretrained', 'labs_model',
       'weight_decay', 'learning_rate', 'epoch', 'val_loss',
       'val_true_cxr_acc_at_1', 'val_true_cxr_acc_at_5', 'val_true_cxr_acc_at_10',
       'val_label_acc_at_1', 'val_label_acc_at_5', 'val_label_acc_at_10',
       'val_label_precision_at_1', 'val_label_precision_at_5', 'val_label_precision_at_10',
        'run_name', 'ckpt_pt', 'wandb_path']
df = df[col_to_keep]

In [4]:
idx = df.groupby(['loss_fn'])['val_loss'].idxmin()
df.loc[idx]

,loss_fn,pretrained,labs_model,weight_decay,learning_rate,epoch,val_loss,val_true_cxr_acc_at_1,val_true_cxr_acc_at_5,val_true_cxr_acc_at_10,val_label_acc_at_1,val_label_acc_at_5,val_label_acc_at_10,val_label_precision_at_1,val_label_precision_at_5,val_label_precision_at_10,run_name,ckpt_pt,wandb_path
9823,clip,False,mlp,1.0,0.001,23,15.063691,0.04,0.40,0.44,0.16,0.56,0.68,0.16,0.136,0.096,20240428_070923_1837,/gpfs/scratch/as16583/ckpts/cxr_prediction/20240428_070923_1837/epoch=23-val_loss=15.0637.ckpt,https://wandb.ai/rajesh-lab/symile/runs/ybmg2nnf
1370,symile,False,mlp,0.5,0.005,70,4.311456,0.12,0.32,0.44,0.24,0.52,0.64,0.24,0.120,0.084,20240430_174626_1994,/gpfs/scratch/as16583/ckpts/cxr_prediction/20240430_174626_1994/epoch=70-val_loss=4.3115.ckpt,https://wandb.ai/rajesh-lab/symile/runs/ndxfgurw
17334,symile-all-negs,False,mlp,0.5,0.005,34,9.683397,0.08,0.28,0.40,0.20,0.48,0.64,0.20,0.096,0.072,20240506_233330_4179,/gpfs/data/ranganathlab/cxr_prediction_ckpts/20240506_233330_4179/epoch=34-val_loss=9.6834.ckpt,https://wandb.ai/rajesh-lab/symile/runs/war8710u

In [5]:
df[df['loss_fn']=="symile"].sort_values(by="val_loss", ascending=True).head(1)

,loss_fn,pretrained,labs_model,weight_decay,learning_rate,epoch,val_loss,val_true_cxr_acc_at_1,val_true_cxr_acc_at_5,val_true_cxr_acc_at_10,val_label_acc_at_1,val_label_acc_at_5,val_label_acc_at_10,val_label_precision_at_1,val_label_precision_at_5,val_label_precision_at_10,run_name,ckpt_pt,wandb_path
1370,symile,False,mlp,0.5,0.005,70,4.311456,0.12,0.32,0.44,0.24,0.52,0.64,0.24,0.12,0.084,20240430_174626_1994,/gpfs/scratch/as16583/ckpts/cxr_prediction/20240430_174626_1994/epoch=70-val_loss=4.3115.ckpt,https://wandb.ai/rajesh-lab/symile/runs/ndxfgurw

In [4]:
idx = df.groupby(['loss_fn', 'weight_decay', 'learning_rate'])['val_true_cxr_acc_at_1'].idxmax()
df.loc[idx]

,loss_fn,pretrained,labs_model,weight_decay,learning_rate,epoch,val_loss,val_true_cxr_acc_at_1,val_true_cxr_acc_at_5,val_true_cxr_acc_at_10,val_label_acc_at_1,val_label_acc_at_5,val_label_acc_at_10,val_label_precision_at_1,val_label_precision_at_5,val_label_precision_at_10,run_name,ckpt_pt,wandb_path
8824,clip,False,mlp,0.1,0.01,24,15.424027,0.20,0.28,0.28,0.20,0.36,0.64,0.20,0.088,0.088,20240428_054506_3065,/gpfs/scratch/as16583/ckpts/cxr_prediction/20240428_054506_3065/epoch=24-val_loss=15.4240.ckpt,https://wandb.ai/rajesh-lab/symile/runs/44w9vmsz
839,symile,False,mlp,0.1,0.01,39,4.641066,0.20,0.48,0.52,0.24,0.72,0.84,0.24,0.160,0.104,20240427_235312_1971,/gpfs/scratch/as16583/ckpts/cxr_prediction/20240427_235312_1971/epoch=39-val_loss=4.6411.ckpt,https://wandb.ai/rajesh-lab/symile/runs/uld2rmme
16868,symile-all-negs,False,mlp,0.1,0.01,68,20.550314,0.32,0.44,0.52,0.36,0.56,0.80,0.36,0.144,0.120,20240506_213158_4943,/gpfs/data/ranganathlab/cxr_prediction_ckpts/20240506_213158_4943/epoch=68-val_loss=20.5503.ckpt,https://wandb.ai/rajesh-lab/symile/runs/bir4csof

In [7]:
df[df['loss_fn']=="symile"].sort_values(by="val_true_cxr_acc_at_1", ascending=False).head(1)

,loss_fn,pretrained,labs_model,weight_decay,learning_rate,epoch,val_loss,val_true_cxr_acc_at_1,val_true_cxr_acc_at_5,val_true_cxr_acc_at_10,val_label_acc_at_1,val_label_acc_at_5,val_label_acc_at_10,val_label_precision_at_1,val_label_precision_at_5,val_label_precision_at_10,run_name,ckpt_pt,wandb_path
1918,symile,False,mlp,1.0,0.0005,18,4.482643,0.2,0.4,0.48,0.28,0.64,0.8,0.28,0.16,0.108,20240428_020718_4141,/gpfs/scratch/as16583/ckpts/cxr_prediction/20240428_020718_4141/epoch=18-val_loss=4.4826.ckpt,https://wandb.ai/rajesh-lab/symile/runs/17sv4y7b