In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("tuning_runs.csv")

In [3]:
df

,run_name,loss_fn,ckpt_pt,epoch,val_loss,val_acc_at_1,val_acc_at_5,val_acc_at_10,pretrained,weight_decay,learning_rate,wandb_path
0,20240426_145455_8068,symile,/gpfs/scratch/as16583/ckpts/risk_prediction/20...,0,5.797836,0.001283,0.024922,0.266813,False,0.001,0.0100,https://wandb.ai/rajesh-lab/symile/runs/cxnm6njs
1,20240426_145455_8068,symile,/gpfs/scratch/as16583/ckpts/risk_prediction/20...,1,5.589696,0.015027,0.066520,0.311893,False,0.001,0.0100,https://wandb.ai/rajesh-lab/symile/runs/cxnm6njs
2,20240426_145455_8068,symile,/gpfs/scratch/as16583/ckpts/risk_prediction/20...,2,5.663314,0.013744,0.048745,0.288254,False,0.001,0.0100,https://wandb.ai/rajesh-lab/symile/runs/cxnm6njs
3,20240426_145455_8068,symile,/gpfs/scratch/as16583/ckpts/risk_prediction/20...,3,5.139569,0.102804,0.275243,0.554151,False,0.001,0.0100,https://wandb.ai/rajesh-lab/symile/runs/cxnm6njs
4,20240426_145455_8068,symile,/gpfs/scratch/as16583/ckpts/risk_prediction/20...,4,5.311912,0.166209,0.398204,0.634964,False,0.001,0.0100,https://wandb.ai/rajesh-lab/symile/runs/cxnm6njs
...,...,...,...,...,...,...,...,...,...,...,...,...
3195,20240426_231036_0336,clip,/gpfs/scratch/as16583/ckpts/risk_prediction/20...,45,21.952612,0.172806,0.598314,0.858347,True,1.000,0.0005,https://wandb.ai/rajesh-lab/symile/runs/kck7e8jz
3196,20240426_231036_0336,clip,/gpfs/scratch/as16583/ckpts/risk_prediction/20...,46,21.455410,0.115082,0.486531,0.785596,True,1.000,0.0005,https://wandb.ai/rajesh-lab/symile/runs/kck7e8jz
3197,20240426_231036_0336,clip,/gpfs/scratch/as16583/ckpts/risk_prediction/20...,47,18.853338,0.193879,0.664651,0.914055,True,1.000,0.0005,https://wandb.ai/rajesh-lab/symile/runs/kck7e8jz
3198,20240426_231036_0336,clip,/gpfs/scratch/as16583/ckpts/risk_prediction/20...,48,18.056246,0.254352,0.736302,0.934396,True,1.000,0.0005,https://wandb.ai/rajesh-lab/symile/runs/kck7e8jz
3199,20240426_231036_0336,clip,/gpfs/scratch/as16583/ckpts/risk_prediction/20...,49,19.226135,0.289720,0.750596,0.943925,True,1.000,0.0005,https://wandb.ai/rajesh-lab/symile/runs/kck7e8jz

In [4]:
symile_df = df[df["loss_fn"] == "symile"]
clip_df = df[df["loss_fn"] == "clip"]

In [6]:
# symile_df.groupby(["learning_rate", "weight_decay"]).max()
# group by learning rate and weight decay, and return the full row that corresponds to min over val loss
# Group by 'learning_rate' and 'weight_decay', then find the index of the min 'val_loss'
idx = df.groupby(['loss_fn'])['val_acc_at_1'].idxmax()

# Retrieve the rows corresponding to these indices
result_df = df.loc[idx]
result_df[['loss_fn','pretrained','learning_rate', 'weight_decay', 'val_loss', 'val_acc_at_1', 'val_acc_at_5', 'val_acc_at_10', 'ckpt_pt']]

,loss_fn,pretrained,learning_rate,weight_decay,val_loss,val_acc_at_1,val_acc_at_5,val_acc_at_10,ckpt_pt
3147,clip,True,0.001,1.0,16.183956,0.391057,0.835074,0.958769,/gpfs/scratch/as16583/ckpts/risk_prediction/20...
1422,symile,True,0.010,1.0,5.672828,0.351109,0.702217,0.972146,/gpfs/scratch/as16583/ckpts/risk_prediction/20...

## symile

In [5]:
symile_df

,run_name,loss_fn,ckpt_pt,epoch_number,val_loss,val_acc_at_1,val_acc_at_5,val_acc_at_10,weight_decay,learning_rate,wandb_path
0,20240421_130526_6972,symile,/gpfs/scratch/as16583/ckpts/risk_prediction/20...,0,5.375611,0.273044,0.618105,0.831592,0.0,0.00100,https://wandb.ai/rajesh-lab/symile/runs/fvrh9pzl
1,20240421_130526_6972,symile,/gpfs/scratch/as16583/ckpts/risk_prediction/20...,1,5.180768,0.304563,0.594649,0.823896,0.0,0.00100,https://wandb.ai/rajesh-lab/symile/runs/fvrh9pzl
2,20240421_130526_6972,symile,/gpfs/scratch/as16583/ckpts/risk_prediction/20...,2,5.358886,0.347260,0.699285,0.924867,0.0,0.00100,https://wandb.ai/rajesh-lab/symile/runs/fvrh9pzl
3,20240421_130526_6972,symile,/gpfs/scratch/as16583/ckpts/risk_prediction/20...,3,4.967637,0.189115,0.415246,0.661169,0.0,0.00100,https://wandb.ai/rajesh-lab/symile/runs/fvrh9pzl
4,20240421_130526_6972,symile,/gpfs/scratch/as16583/ckpts/risk_prediction/20...,4,4.872858,0.313176,0.664651,0.888583,0.0,0.00100,https://wandb.ai/rajesh-lab/symile/runs/fvrh9pzl
...,...,...,...,...,...,...,...,...,...,...,...
995,20240422_024625_0307,symile,/gpfs/scratch/as16583/ckpts/risk_prediction/20...,45,8.304611,0.265530,0.645776,0.876672,0.1,0.00005,https://wandb.ai/rajesh-lab/symile/runs/gjsglhgn
996,20240422_024625_0307,symile,/gpfs/scratch/as16583/ckpts/risk_prediction/20...,46,7.813780,0.210738,0.575224,0.811435,0.1,0.00005,https://wandb.ai/rajesh-lab/symile/runs/gjsglhgn
997,20240422_024625_0307,symile,/gpfs/scratch/as16583/ckpts/risk_prediction/20...,47,8.400788,0.156863,0.412864,0.653289,0.1,0.00005,https://wandb.ai/rajesh-lab/symile/runs/gjsglhgn
998,20240422_024625_0307,symile,/gpfs/scratch/as16583/ckpts/risk_prediction/20...,48,9.281193,0.210189,0.511087,0.744548,0.1,0.00005,https://wandb.ai/rajesh-lab/symile/runs/gjsglhgn
999,20240422_024625_0307,symile,/gpfs/scratch/as16583/ckpts/risk_prediction/20...,49,8.359189,0.218802,0.563130,0.792377,0.1,0.00005,https://wandb.ai/rajesh-lab/symile/runs/gjsglhgn

In [7]:
# VAL LOSS, ASCENDING TRUE
symile_df.sort_values(by="val_loss", ascending=True).head(1)

,run_name,loss_fn,ckpt_pt,epoch_number,val_loss,val_acc_at_1,val_acc_at_5,val_acc_at_10,weight_decay,learning_rate,wandb_path
220,20240421_151725_5541,symile,/gpfs/scratch/as16583/ckpts/risk_prediction/20...,20,4.208516,0.267363,0.615723,0.836357,0.0001,0.001,https://wandb.ai/rajesh-lab/symile/runs/kox4d7xh

In [13]:
# VAL ACC AT 1, ASCENDING FALSE
symile_df.sort_values(by="val_acc_at_1", ascending=False).head(1)

,run_name,loss_fn,ckpt_pt,epoch_number,val_loss,val_acc_at_1,val_acc_at_5,val_acc_at_10,weight_decay,learning_rate,wandb_path
2,20240421_130526_6972,symile,/gpfs/scratch/as16583/ckpts/risk_prediction/20...,2,5.358886,0.34726,0.699285,0.924867,0.0,0.001,https://wandb.ai/rajesh-lab/symile/runs/fvrh9pzl

In [9]:
# VAL ACC AT 5, ASCENDING FALSE
symile_df.sort_values(by="val_acc_at_5", ascending=False).head(1)

,run_name,loss_fn,ckpt_pt,epoch_number,val_loss,val_acc_at_1,val_acc_at_5,val_acc_at_10,weight_decay,learning_rate,wandb_path
33,20240421_130526_6972,symile,/gpfs/scratch/as16583/ckpts/risk_prediction/20...,33,5.443552,0.319406,0.702767,0.93971,0.0,0.001,https://wandb.ai/rajesh-lab/symile/runs/fvrh9pzl

In [10]:
# VAL ACC AT 10, ASCENDING FALSE
symile_df.sort_values(by="val_acc_at_10", ascending=False).head(1)

,run_name,loss_fn,ckpt_pt,epoch_number,val_loss,val_acc_at_1,val_acc_at_5,val_acc_at_10,weight_decay,learning_rate,wandb_path
297,20240421_152024_1183,symile,/gpfs/scratch/as16583/ckpts/risk_prediction/20...,47,9.085451,0.282756,0.684992,0.953271,0.0001,0.0005,https://wandb.ai/rajesh-lab/symile/runs/24kq2x90

## clip

In [6]:
clip_df

,run_name,loss_fn,ckpt_pt,epoch_number,val_loss,val_acc_at_1,val_acc_at_5,val_acc_at_10,weight_decay,learning_rate,wandb_path
1000,20240421_132103_7385,clip,/gpfs/scratch/as16583/ckpts/risk_prediction/20...,0,16.481934,0.267180,0.641195,0.844237,0.0,0.00100,https://wandb.ai/rajesh-lab/symile/runs/5o807xpy
1001,20240421_132103_7385,clip,/gpfs/scratch/as16583/ckpts/risk_prediction/20...,1,16.249510,0.161078,0.320323,0.576141,0.0,0.00100,https://wandb.ai/rajesh-lab/symile/runs/5o807xpy
1002,20240421_132103_7385,clip,/gpfs/scratch/as16583/ckpts/risk_prediction/20...,2,16.063299,0.257651,0.563130,0.767088,0.0,0.00100,https://wandb.ai/rajesh-lab/symile/runs/5o807xpy
1003,20240421_132103_7385,clip,/gpfs/scratch/as16583/ckpts/risk_prediction/20...,3,16.115723,0.277442,0.599047,0.824995,0.0,0.00100,https://wandb.ai/rajesh-lab/symile/runs/5o807xpy
1004,20240421_132103_7385,clip,/gpfs/scratch/as16583/ckpts/risk_prediction/20...,4,15.973129,0.256734,0.545904,0.774968,0.0,0.00100,https://wandb.ai/rajesh-lab/symile/runs/5o807xpy
...,...,...,...,...,...,...,...,...,...,...,...
1995,20240422_013602_9292,clip,/gpfs/scratch/as16583/ckpts/risk_prediction/20...,45,18.293640,0.213671,0.536375,0.682609,0.1,0.00005,https://wandb.ai/rajesh-lab/symile/runs/3vt3xhd8
1996,20240422_013602_9292,clip,/gpfs/scratch/as16583/ckpts/risk_prediction/20...,46,18.376429,0.256551,0.548653,0.688840,0.1,0.00005,https://wandb.ai/rajesh-lab/symile/runs/3vt3xhd8
1997,20240422_013602_9292,clip,/gpfs/scratch/as16583/ckpts/risk_prediction/20...,47,18.406721,0.261865,0.538391,0.665384,0.1,0.00005,https://wandb.ai/rajesh-lab/symile/runs/3vt3xhd8
1998,20240422_013602_9292,clip,/gpfs/scratch/as16583/ckpts/risk_prediction/20...,48,18.477720,0.132857,0.466740,0.636797,0.1,0.00005,https://wandb.ai/rajesh-lab/symile/runs/3vt3xhd8
1999,20240422_013602_9292,clip,/gpfs/scratch/as16583/ckpts/risk_prediction/20...,49,18.416389,0.238226,0.589152,0.742899,0.1,0.00005,https://wandb.ai/rajesh-lab/symile/runs/3vt3xhd8

In [22]:
# VAL LOSS, ASCENDING TRUE
clip_df.sort_values(by="val_loss", ascending=True).head(1)

,run_name,loss_fn,ckpt_pt,epoch_number,val_loss,val_acc_at_1,val_acc_at_5,val_acc_at_10,weight_decay,learning_rate,wandb_path
1215,20240421_152523_9052,clip,/gpfs/scratch/as16583/ckpts/risk_prediction/20...,15,14.989574,0.23053,0.542239,0.79256,0.0001,0.001,https://wandb.ai/rajesh-lab/symile/runs/m2llvcbn

In [27]:
# VAL ACC AT 1, ASCENDING FALSE
clip_df.sort_values(by="val_acc_at_1", ascending=False).head(1)

,run_name,loss_fn,ckpt_pt,epoch_number,val_loss,val_acc_at_1,val_acc_at_5,val_acc_at_10,weight_decay,learning_rate,wandb_path
1837,20240421_233259_8398,clip,/gpfs/scratch/as16583/ckpts/risk_prediction/20...,37,23.158213,0.363386,0.820597,0.961334,0.1,0.001,https://wandb.ai/rajesh-lab/symile/runs/b245r6xy

In [17]:
# VAL ACC AT 5, ASCENDING FALSE
clip_df.sort_values(by="val_acc_at_5", ascending=False).head(1)

,run_name,loss_fn,ckpt_pt,epoch_number,val_loss,val_acc_at_1,val_acc_at_5,val_acc_at_10,weight_decay,learning_rate,wandb_path
1498,20240421_192728_0211,clip,/gpfs/scratch/as16583/ckpts/risk_prediction/20...,48,29.163345,0.325637,0.831592,0.942276,0.001,0.0005,https://wandb.ai/rajesh-lab/symile/runs/s1qept2w

In [18]:
# VAL ACC AT 10, ASCENDING FALSE
clip_df.sort_values(by="val_acc_at_10", ascending=False).head(1)

,run_name,loss_fn,ckpt_pt,epoch_number,val_loss,val_acc_at_1,val_acc_at_5,val_acc_at_10,weight_decay,learning_rate,wandb_path
1295,20240421_172634_4873,clip,/gpfs/scratch/as16583/ckpts/risk_prediction/20...,45,29.228878,0.161994,0.686275,0.968481,0.0001,0.0005,https://wandb.ai/rajesh-lab/symile/runs/72dmd5vu